### ISSUE TITLE
Can this library be used on a read-only filesystem?

### ISSUE THREAD

**Issue by Kadigan** [maennchen/ZipStream-PHP#100]
Can this be used in a location that PHP doesn't have write access to?

Does the library even _need_ write access?

**Comment by NicolasCARPi** [comment]
That's a good question. AFAIK it should be possible. One could test it in a read-only docker container.

**Comment by Kadigan** [comment]
I've done basic testing under macOS and it seems to behave, but it would be good to have as much tested and stated in the README.

**Comment by NicolasCARPi** [comment]
I'll try to whip up a test case later :)

**Comment by maennchen** [comment]
This can clearly be answered with yes. There are no temporary or similar files used by the library at all.

I don't think that this needs to be in the README since this is quite specific.
