### ISSUE TITLE
Set Unix file permissions on specific file in an archive (?)

### ISSUE THREAD

**Issue by PavelDonskikh** [maennchen/ZipStream-PHP#101]
# Description of the problem
Is there any way to set Unix file permissions for a specific files in an archive?
I.e. if I use the ZipStream and successfully create a .zip archive, then I unzip it on Ubuntu, currently all the permissions I have are 644.
Is there a way to have 640 permissions for some specific file right upon the unzip without additional chmod?
Thank you!

# Example code
some sample code:
$zip = new ZipStream\ZipStream($name, $streamOptions);
foreach ($files as $file) {
    $path = $location . '/' . $file;
    if ($streamRead = fopen($path , 'r')) {
        $zip->addFileFromStream($file, $streamRead);
    }
}
$zip->finish();

# Informations
* ZipStream-PHP version:
    "name": "maennchen/zipstream-php",
    "version": "v0.5.2"
* PHP version:
    7.1

**Comment by NicolasCARPi** [comment]
Hello,

No there is no way to have different permissions in the zip archive for different files. And this has to do with Zip itself, not this library (see [this answer](https://unix.stackexchange.com/a/313663)).

You might want to try `tar` archives instead ;)

~Nico

**Comment by PavelDonskikh** [comment]
> Hello,
> 
> No there is no way to have different permissions in the zip archive for different files. And this has to do with Zip itself, not this library (see [this answer](https://unix.stackexchange.com/a/313663)).
> 
> You might want to try `tar` archives instead ;)
> 
> ~Nico

Thank you!
