### ISSUE TITLE
Allowed memory size exhausted (version 0.5)

### ISSUE THREAD

**Issue by dcruceanu** [maennchen/ZipStream-PHP#102]
Hello, I am using ZipStream in Symfony. Even if I use ***addFile*** or **addFileFromStream** to add around 300 files in the zip, I am getting the following error:

> Fatal Error : Error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 60579248 bytes)

Code:
`
         
        foreach ($arrayOfBlobs as $name => $blob) {
            $zip->addFileFromStream($name, ($blob->getContentStream()));
        }
        
        $zip->finish();`

This is working fine for 5 or 60 files. I didn't found the upper limit, but I know for sure that it fails when you have around 300 documents...

The version used it's 0.5.
I also tried it with the dev-master version, but with no success...

**Comment by NicolasCARPi** [comment]
Hello,

Thanks for reporting this issue.

> I also tried it with the dev-master version, but with no success...

You got the same error with dev-master?

I'll try and investigate what's possible to do, but it might be tricky.

**Comment by dcruceanu** [comment]
If I'm using the dev-master, I'm receiving **Warning: rewind(): stream does not support seeking**
My code:
`$file = fopen("azure://...", "w");

  $zipOptions = new Archive();
        $zipOptions
            ->setOutputStream($file);
        
        $zip = new ZipStream(
            $name,
            $zipOptions
        );
        
        /** @var GetBlobResult $blob */
        foreach ($arrayOfBlobs as $name => $blob) {
            $zip->addFileFromStream($name, ($blob->getContentStream()));
        }
        
        $zip->finish();`

**Comment by NicolasCARPi** [comment]
The stream must be conforming to PSR-7, which apparently it does not.

**Comment by maennchen** [comment]
@NicolasCARPi 

Streams are not always seekable. Not even in PSR.

https://www.php-fig.org/psr/psr-7/
> Streams expose their capabilities using three methods: isReadable(), isWritable(), and isSeekable(). These methods can be used by stream collaborators to determine if a stream is capable of their requirements.

A good question would be, why do we need to seek streams in the new major version. Before it worked without.

**Comment by maennchen** [comment]
@NicolasCARPi 

If you want to trace the seeking issue farther, please open a new ticket.

As for the reported issue: Do you plan to support the last major version further? Otherwise please close the issue.

**Comment by NicolasCARPi** [comment]
No, only the latest stable is supported.
