### ISSUE TITLE
Functionality request and project status

### ISSUE THREAD

**Issue by flindvall** [maennchen/ZipStream-PHP#103]
Before posting this I read #79 and got the impression that the project has reached stable status but I can only see alpha1 and alpha2 for version 1.0.0 with composer.
Is there any special reason why the library is still in alpha stage and if so is there a timeline for when it will reach RC or stable?
Also, are there any plans on implementing outputting to PSR7 response?

Sincerely,
/Fredrik

**Comment by NicolasCARPi** [comment]
I agree that it seems reasonable to release a stable 1.0.0 version now, as I believe no major bug exist in the library. But that's something only @maennchen can do ;)

**Comment by maennchen** [comment]
@NicolasCARPi If you believe it to be ready for stable, I'll do a release :)

**Comment by maennchen** [comment]
@NicolasCARPi If you want I can give you access to packagist as well.

**Comment by NicolasCARPi** [comment]
> If you believe it to be ready for stable, I'll do a release :)

:+1: 

> If you want I can give you access to packagist as well.

Sure why not :)

**Comment by maennchen** [comment]
@NicolasCARPi What is your username on packagist?

**Comment by NicolasCARPi** [comment]
@maennchen NicolasCARPi (just created it)

**Comment by NicolasCARPi** [comment]
@flindvall The 1.0.0 version has been tagged. You can now use `"maennchen/zipstream-php": "^1.0"` in your `composer.json` file :)

As for PSR-7, it is not in the pipes but that might be something that can be added. Please open another issue for this specific question describing your use case (better to have one topic per issue, and I'll close this one).
