### ISSUE TITLE
Automatic output of HTTP headers

### ISSUE THREAD

**Issue by pfofi** [maennchen/ZipStream-PHP#107]
Since commit [fbe6ba5](https://github.com/maennchen/ZipStream-PHP/commit/fbe6ba59f8b9963dde96bc09ac40de649145a5d1#diff-3b3e03a6fce80d7f70706fab060b492aL245) HTTP headers are not generated if only an output filename *or* the `sendHttpHeaders` option are set. I'm not sure if this was intended, as it is not reflected by the docs.

I prepared a branch for each case.
- change was intentional, fix documentation: pfofi@424d248
- change was unintended, fix behavior: pfofi@8db36e9

Feel free to pull the desired changes or let me know for which branch I should open a pull request.

## Example
The usage example of the current [README.md](https://github.com/maennchen/ZipStream-PHP/blob/7fa70b22dc8468ff9af83d37568fbb6f2589bcf3/README.md#usage-and-options) outputs the raw ZIP archive without headers.

**Comment by NicolasCARPi** [comment]
Hello,

I would go with option 1: fix the readme. The readme example should be complete (so with headers).

Can you do a PR for that please?
