### ISSUE TITLE
Issues with the Version >1.0 and streams

### ISSUE THREAD

**Issue by gullevek** [maennchen/ZipStream-PHP#117]
# Description of the problem

Since updating to the newest version of zipStream there is no way to add temporary files to the zip anymore.

I use the demo code from the git start page

# Example code

```php
require 'vendor/autoload.php';
$opt = new ZipStream\Option\Archive();
$opt->setSendHttpHeaders(true);
$zip = new ZipStream\ZipStream('example.'.time().'.zip', $opt);

$fp = tmpfile();
fwrite($fp, 'The quick brown fox jumped over the lazy dog.');
fwrite($fp, 'I Am a nuclear power plant.');
// fseek($fp, 0);
rewind($fp);
$zip->addFileFromStream('goodbye.txt', $fp);
fclose($fp);

$zip->addFileFromPath('test.txt', 'test.txt');

$zip->finish();
```
This creates a zip file that is not openable in any ZIP (windows 10 or Mac os 10.14.4):
(Error 1 - Operation not permitted.)
On the command line I get the following output:

```
Archive:  example.1558402559.zip
warning [example.1558402559.zip]:  9299 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  9299
  (attempting to re-compensate)
  inflating: goodbye.txt             
file #2:  bad zipfile offset (local header sig):  110
  (attempting to re-compensate)
  inflating: test.txt 
```
If I however use the previous version of zipStream (0.3.0) then I can create a working zip file with the same code.

Also filesize of the zip files are different.
New Version: 9,599 bytes
Old Version 349 bytes

The files inside are 72 bytes and 17 bytes.

Removing the tmpfile/addFileFromStream will lead to a working ZIP file again.

# Informations

* ZipStream-PHP version: 1.1.0
* PHP version: 7.3 and 7.2

Please include any supplemental information you deem relevant to this issue.

**Comment by NicolasCARPi** [comment]
Hello,

That's weird because it works fine on my computer. I tried the code you provided, the zip is good and there are no errors.

BTW: the fclose() call emits a warning, can be replaced by:

~~~php
if (is_resource($fp)) {
    fclose($fp);
}
~~~

PHP 7.3.5 (cli) on Archlinux. The code is in `a.php`, then `php -S localhost:7000`, and `curl http://localhost:7000/a.php -o file.zip`.

![2019-05-21-142803_538x130_scrot](https://user-images.githubusercontent.com/3043706/58096121-a9966600-7bd4-11e9-8abe-96e44a14dd8a.png)

**Comment by gullevek** [comment]
I tried it on two different systems.
* Debian/stable with backported PHP 7.3
* Debian/testing with debian PHP 7.3

and both worked fine.

It seems my self compiled install has some issues with the zlib library or some other issue.

**Comment by NicolasCARPi** [comment]
Ok, closing then.
