### ISSUE TITLE
HTML code in ZIP archive

### ISSUE THREAD

**Issue by abujalka** [maennchen/ZipStream-PHP#118]
Hi, I have this problem:
I have a code with which I create a zip archive to which I upload various files. Everything works as it should, but I can't open a zip archive because it's corrupted.
If I open a zip archive in a text editor, the html code from my page is at the end.
How do I remove this html code when creating a zip archive?

My code : 

~~~php
$options = new ZipStream\Option\Archive();
$options->setSendHttpHeaders(TRUE);
$zip = new ZipStream\ZipStream('name.zip',$options);
$zip->finish();
~~~

* ZipStream-PHP version: 1.1.0
* PHP version: 7.2.4

**Comment by NicolasCARPi** [comment]
Might be a good idea to look into separating your php code from your html code ;)

Also note that boolean in php is lowercase (`true`).

Closing this as it's not an issue with this library but feel free to comment on this issue if something is not clear.

**Comment by abujalka** [comment]
Hi, I'm a beginner and can't think of how to separate html code from php.
I have the app in nette.
I have a button on the page that points to handleExport.
And in that handle I have the code I wrote above.
How do I separate it from html?

Changing to lowercase did not cause any change.

Thanks

**Comment by NicolasCARPi** [comment]
For instance you can have a page called "makeZip.php", and you make a link that points to this page with the necessary information in the URL. This page only contains the PHP code and outputs the ZIP.
