### ISSUE TITLE
Stream zip to s3 with correct permissions.

### ISSUE THREAD

**Issue by webbash** [maennchen/ZipStream-PHP#120]
When I tried to upload a zip archive directly to s3 via stream, I faced the problem of incorrect permissions, so after uploading the file to the cloud, it was not readable. The solution to this problem is to set the correct ACL rights. I hope someone can help. Here is an example:

```php
$path = "s3://{$adapter->getBucket()}/{$this->getArchivePath()}";

$outputContext = stream_context_create([
    's3' => ['ACL' => 'public-read'],
]);

fopen($path, 'w', null, $outputContext);
```

**Comment by NicolasCARPi** [comment]
Hello,

Thanks, I have added a note on the wiki: https://github.com/maennchen/ZipStream-PHP/wiki/Symfony-example#uploading-a-file
