### ISSUE TITLE
Integration with FlySystem

### ISSUE THREAD

**Issue by mathieutu** [maennchen/ZipStream-PHP#121]
# Description of the problem

Hi, thanks for this package.

I'm trying to upload the generated zip to disks such as ftp, google, aws, etc.
Flysystem from The PHP League is a great library to do that, and it handles natively streams via its `putStream` method.

This method waits for a stream argument which is a resource object:
https://flysystem.thephpleague.com/docs/usage/filesystem-api/#write-or-update-files-using-a-stream

I didn't manage to make it working with ZipStream, and have no idea to how to do that.

I've tried to pass the ZipStream object, but it's not a resource, I've tried to pass the resource from `$opt->getOutputStream()` before and after finish.

If it's possible, and when I'll success to make it working, I could make a PR with some documentation examples.

Thanks. 
Matt'

# Informations
* ZipStream-PHP version: 1.1
* PHP version: 7.3

**Comment by maennchen** [comment]
You could try to pass a custom `outputStream` to the `ZipStream\Option\Archive`. This could for example be `php://temp` or `php://memory`.

https://www.php.net/manual/en/wrappers.php.php

**Comment by mathieutu** [comment]
Hi. Thanks for your answer.
I'm sorry but I really don't understand how to handle that. 😕

I've tried many things like: 

```php
$zipStreamOptions = new Archive();
$zipStreamOptions->setOutputStream(fopen('php://memory', 'wb'));
$zipStream = new ZipStream('test.zip', $zipStreamOptions);
$zipStream->addFile('foo.txt', 'test text');
\Storage::disk('local')->putStream('test.zip', fopen('php://memory', 'rb'));
$zipStream->finish();
```
(laravel storage system, based on flysystem here)

The file is created, but when trying to extract it, I have another archive with cpgz extension.

Actually I've never worked with streams except basic usages, so I'm sorry if my question is a dumb one.

Thanks again.

**Comment by maennchen** [comment]
I think it should work with a little adjustment:

```php
$tempStream = fopen('php://memory', 'w+');
$zipStreamOptions = new Archive();
$zipStreamOptions->setOutputStream($tempStream);
$zipStream = new ZipStream('test.zip', $zipStreamOptions);
$zipStream->addFile('foo.txt', 'test text');
\Storage::disk('local')->putStream('test.zip', $tempStream);
$zipStream->finish();
fclose($tempStream);
```

**Comment by mathieutu** [comment]
Actually I had tried this one and:

```bash
unzip test.zip
Archive:  test.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  test.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of test.zip or
        test.zip.zip, and cannot find test.zip.ZIP, period.
```

**Comment by maennchen** [comment]
How big is the resulting zip file? Is there any content at all?

**Comment by maennchen** [comment]
Maybe you need to `rewind($tempStream)` before calling `putStream`.

**Comment by mathieutu** [comment]
Yeah, with this last example, it isn't empty (48B).

rewind doesn't change anything 😕.

**Comment by maennchen** [comment]
It doesn't seem to be a zip file... Can you look inside the file with a normal text editor?

**Comment by mathieutu** [comment]
It seems to be a binary file: 

```
cat test.zip
P�[�N�pE
        	foo.txt+I-.Q(I�(%
```

**Comment by maennchen** [comment]
Ah wait, put the `finish`call before the `putStream` call.

**Comment by mathieutu** [comment]
And again the cpgz file (unzip has much more details, cf below) 😅 

```php
$tempStream = fopen('php://memory', 'w+');

$zipStreamOptions = new Archive();
$zipStreamOptions->setOutputStream($tempStream);

$zipStream = new ZipStream('test.zip', $zipStreamOptions);
$zipStream->addFile('foo.txt', 'test text');

rewind($tempStream);

$zipStream->finish();

\Storage::disk('local')->putStream('test.zip', $tempStream);

fclose($tempStream);
```

and 
```bash
cat test.zip
P�^�N�pE
        	 foo.txtPK50%
la test.zip
-rw-r--r--@ 1 mathieutu  staff    75B Jun 12 11:54 test.zip

unzip test.zip
Archive:  test.zip
error [test.zip]:  missing 48 bytes in zipfile
  (attempting to process anyway)
error [test.zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
  (attempting to re-compensate)
file #1:  bad zipfile offset (local header sig):  0
  (attempting to re-compensate)
error [test.zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

**Comment by maennchen** [comment]
```php
// Open Stream only once for read and write since it's a memory stream and
// the content is lost when closing the stream / opening another one
$tempStream = fopen('php://memory', 'w+');

// Init Options
$zipStreamOptions = new Archive();
$zipStreamOptions->setOutputStream($tempStream);

// Create Zip Archive
$zipStream = new ZipStream('test.zip', $zipStreamOptions);
$zipStream->addFile('foo.txt', 'test text');
$zipStream->finish();

// Rewing Stream to the start of the file
rewind($tempStream);

// Store File
\Storage::disk('local')->putStream('test.zip', $tempStream);

// Close Stream
fclose($tempStream);
```

**Comment by mathieutu** [comment]
And it's a success! 🎉  

Thank you very much for your help, and for the comments. 

Do you have any interesting readings about streams in php? (Actually I'm used to work with them with NodeJs, but it's a bit confusing for me in php.)

Maybe it could be good to add something about that in documentation, or even a feature that handle it in the package.

Do you want a PR? An idea of the wanted implementation?

**Comment by maennchen** [comment]
Streams (called Resource) in PHP is actually quite a broad topic. You could for example not only open a stream to a file or memory, but instead send the data to [a process or a thousand or places](https://www.php.net/manual/en/resource.php) or even some special streams like [`php://stdin`, `php://fd`](https://www.php.net/manual/en/wrappers.php.php).


I would recommend you to read the docs for specific use cases you need like [`fopen`](https://php.net/manual/en/function.fopen.php).

What do you have in mind with a PR / docs? I think we shouldn't generally explain resources since there's way better places to learn about them.

**Comment by mathieutu** [comment]
Not explain them but at least post the example to use with flysystem (or other than the documented response).

And for a feature, eventually a method like `setStreamForXXX` which set php://memory as output and return it?

**Comment by maennchen** [comment]
An example with FlySystem would be welcome. Would you add this in the wiki?

I don't think that a special method for the `php://memory` stream would be a good idea. It is quite specific for this use case, it does impact the memory limit of PHP and could potentially produce an error therefore. I would rather have that people choose the correct tool for the job themselves in that case.

**Comment by mathieutu** [comment]
Ok, I understand. And what would you use instead of php://memory to do the job?

The need here is to create a zip, and upload it to a provider, in a context where the access to the local filesystem isn't guaranteed.


I can't edit or PR myself the doc, so here is the explanation to insert:

````md
# Save the generated zip.

For saving or uploading the generated zip, you can use the [Flysystem](https://flysystem.thephpleague.com) package, and its many adapters.

For that you will need to provide another stream than the `php://output` default one, and pass it to Flysystem `putStream` method.

```php
// Open Stream only once for read and write since it's a memory stream and
// the content is lost when closing the stream / opening another one
$tempStream = fopen('php://memory', 'w+');

// Init Options
$zipStreamOptions = new Archive();
$zipStreamOptions->setOutputStream($tempStream);

// Create Zip Archive
$zipStream = new ZipStream('test.zip', $zipStreamOptions);
$zipStream->addFile('test.txt', 'text');
$zipStream->finish();

// Store File (see Flysystem documentation, and all its framework integration)
$adapter = new Local(__DIR__.'/path/to/folder'); // Can be any adapter (AWS, Google, Ftp, etc.)
$filesystem = new Filesystem($adapter);

$filesystem->putStream('test.zip', $tempStream)

// Close Stream
fclose($tempStream);
```
````

Thank you again for this package, and the time you took for helping me.

**Comment by maennchen** [comment]
https://github.com/maennchen/ZipStream-PHP/wiki/FlySystem-Example

You could for example use `php://temp` or you could register a custom stream wrapper like [S3](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html).

There are many solutions and depending on the use case any of them could mean advantages & disadvantages.

**Comment by mathieutu** [comment]
Ok thanks!
