### ISSUE TITLE
Archive an existing file

### ISSUE THREAD

**Issue by engharb** [maennchen/ZipStream-PHP#126]
# Description of the problem

I used to create a csv file using League/csv lib. and I want to archive that file, is it possible?

# Example code
```
$csv = Writer::createFromPath('php://temp', 'w+');
```

* ZipStream-PHP version: 1.2
* PHP version: 7.1

**Comment by engharb** [comment]
And is it possible to chunk the file while streaming.

**Comment by engharb** [comment]
I have the following implementation. and I want to chunk my created zip file
```
$response = new StreamedResponse();

$response->setCallback(function () use ($csv, $flush_threshold, $fileName) {

                //initialise zipstream with output zip filename and options.
                $zip = new ZipStream('test.zip');
                $zip->addFile($fileName, $csv->getContent());
                $zip->finish();

               // is it possible to do something like this:
                foreach ($zip->chunk(1024) as $offset => $chunk) {
                    echo $chunk;
                    if ($offset % $flush_threshold === 0) {
                        flush();
                    }
                }     

            });

 return $response->send();
```

**Comment by engharb** [comment]
@maennchen is it possible to chunk a big data in addFile i.e.:
```
$zip->addFile($fileName, function () use ($csv, $flush_threshold) {
                        foreach ($csv->chunk(1024) as $offset => $chunk) {
                            echo $chunk;
                            if ($offset % $flush_threshold === 0) {
                                flush();
                            }
                        }
                    });
```

**Comment by maennchen** [comment]
No, that‘s what Streams are for.

Depending on your use case, you could probably implement a custom stream.

**Comment by engharb** [comment]
@maennchen I tried to find a workaround but no success.

**Comment by maennchen** [comment]
@engharb You need to write a lot more details so that I could help you.

Generally, two ways are available:

* Resources (the thing an `fopen` call returns)
* `StreamInterface` https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php

You need to provide one of those two.

Since this is neither a bug report nor a feature request, I'm going to close this issue.
