### ISSUE TITLE
Add Content-Length header

### ISSUE THREAD

**Issue by vvval** [maennchen/ZipStream-PHP#127]
Is it possible to add a content-length header so users will be notified about the exact size of the downloaded archive before the download ends?

**Comment by maennchen** [comment]
It would be theoretically possible with non-compressed zip files but only if all the contents are clear from the start.

Since this is a library intended for streaming, this is not really the default use case and in my opinion out of scope.

**Comment by NicolasCARPi** [comment]
See related #89.
