### ISSUE TITLE
Zip can't be extracted in Windows WinRAR

### ISSUE THREAD

**Issue by engharb** [maennchen/ZipStream-PHP#129]
# Description of the problem

I used to create and stream my zip file as the following 
```php
$response = new StreamedResponse();
....
$fp = fopen('php://temp', 'r+');

                    foreach ($csv->chunk(1024) as $offset => $chunk) {
                        fputs($fp, $chunk);
                    }
                    // reset the position of file pointer
                    rewind($fp);

                    $options = new Archive();
                    $options->setFlushOutput(true);
                    //initialise zipstream
                    $zip = new ZipStream($type->getName() . ".zip", $options);
                    $zip->addFileFromStream($fileName, $fp);

                    $zip->finish();
                    fclose($fp);
....
return $response;
```

In MacOS works fine, but when I opened the generated zip file using notpad++ I found error printed in the file.

It was from 'fclose($fp);' therefore I want to know if '$zip->finish();' stream and close the stream file or not? I checked the lib code and I did not find any clue.

Please give inform me with a clear clarification.

# Informations

* ZipStream-PHP version: 1.2
* PHP version: 7.1

**Comment by NicolasCARPi** [comment]
Hello,

Yes streams are closed with the `__destruct()` method:

https://github.com/maennchen/ZipStream-PHP/blob/master/src/Stream.php#L25-L28
