### ISSUE TITLE
Seekable exception not thrown

### ISSUE THREAD

**Issue by timnash** [maennchen/ZipStream-PHP#130]
Hello,

I'm using ZipStream to package files streamed from S3.

Originally in testing the zip file would complete and then could not be opened.
Since S3 streams aren't seekable by default I should have set the zero header with $options->setZeroHeader(true) but hadn't done that. However, the seekable exception was never thrown.

* ZipStream-PHP version: 1.0
* PHP version: 7.3

**Comment by timnash** [comment]
I looked into it a little more and 
seekable is being reported true but the guzzle wrapper_data seekable is false.

So is this a problem with how AWS is setting up the stream, or a guzzle problem?

**Comment by timnash** [comment]
Here's a var dump of the metadata.
`array(10) {
  ["timed_out"]=>
  bool(false)
  ["blocked"]=>
  bool(true)
  ["eof"]=>
  bool(false)
  ["wrapper_data"]=>
  object(Aws\S3\StreamWrapper)#88 (11) {
    ["context"]=>
    resource(2) of type (stream-context)
    ["body":"Aws\S3\StreamWrapper":private]=>
    object(GuzzleHttp\Psr7\Stream)#131 (7) {
      ["stream":"GuzzleHttp\Psr7\Stream":private]=>
      resource(17) of type (stream)
      ["size":"GuzzleHttp\Psr7\Stream":private]=>
      NULL
      ["seekable":"GuzzleHttp\Psr7\Stream":private]=>
      bool(false)
      ["readable":"GuzzleHttp\Psr7\Stream":private]=>
      bool(true)
      ["writable":"GuzzleHttp\Psr7\Stream":private]=>
      bool(false)
      ["uri":"GuzzleHttp\Psr7\Stream":private]=>
      string(141) "https://this-is-an-s3-url"
      ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=>
      array(0) {
      }
    }
    ["size":"Aws\S3\StreamWrapper":private]=>
    int(49934)
    ["params":"Aws\S3\StreamWrapper":private]=>
    array(2) {
      ["Bucket"]=>
      string(22) "an-s3-bucket"
      ["Key"]=>
      string(93) "an-s3-key"
    }
    ["mode":"Aws\S3\StreamWrapper":private]=>
    string(1) "r"
    ["objectIterator":"Aws\S3\StreamWrapper":private]=>
    NULL
    ["openedBucket":"Aws\S3\StreamWrapper":private]=>
    NULL
    ["openedBucketPrefix":"Aws\S3\StreamWrapper":private]=>
    NULL
    ["openedPath":"Aws\S3\StreamWrapper":private]=>
    NULL
    ["cache":"Aws\S3\StreamWrapper":private]=>
    NULL
    ["protocol":"Aws\S3\StreamWrapper":private]=>
    string(2) "s3"
  }
  ["wrapper_type"]=>
  string(10) "user-space"
  ["stream_type"]=>
  string(10) "user-space"
  ["mode"]=>
  string(1) "r"
  ["unread_bytes"]=>
  int(0)
  ["seekable"]=>
  bool(true)
  ["uri"]=>
  string(121) "s3://s3uri"
}`

**Comment by NicolasCARPi** [comment]
Hello,

Have you read this: https://github.com/maennchen/ZipStream-PHP/wiki/Symfony-example ?

To make the stream seekable you need:

~~~php
$context = stream_context_create([
    's3' => ['seekable' => true]
]);
~~~

Also, what "Seekable exception" are you talking about?

Can you show your code?

**Comment by timnash** [comment]
Yes, I did see how to make it seekable. I did get the code working fine by using the zero header. The issue is before I was able to get it working, I couldn't figure out why it wasn't because the code never threw the seekable RuntimeException.

In the File->processStreamWithComputedHeader function, it calls Stream->rewind.
Stream->rewind calls Stream->seek, which is supposed to throw a RuntimeException if Stream->isSeekable is false.

In this case Stream->isSeekable is true because the metadata['seekable'] is true (even though it is not seekable [see above, a dump of stream_get_meta_data that is called on Stream:125]).

The metadata['wrapper_data']->body->seekable is false, however.

So I'm not sure if that's an AWS misconfiguration of their stream or if it's a guzzle problem as I haven't looked past this part. I could write up some code to check the way the S3 Stream shows seekable if that would help.

**Comment by NicolasCARPi** [comment]
Well, it looks like guzzle rewind doesn't throw an exception: https://github.com/guzzle/guzzle3/blob/master/src/Guzzle/Stream/StreamInterface.php#L187, whereas the implementation should: https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php#L97

So this might be a Guzzle bug (or maybe it's on purpose...).

**Comment by NicolasCARPi** [comment]
Closing as invalid (see message above).
