### ISSUE TITLE
How do you debug failures?

### ISSUE THREAD

**Issue by jadjoubran** [maennchen/ZipStream-PHP#131]
# Description of the problem
Hey, thanks a lot for the great work on this library! I really appreciate all the documentation and functionality that goes into it.

I'm having an issue in some scenarios that I am unable to debug. The API call is returning a 500 and it feels like there are some silenced errors (@) within this library (maybe?).

When there's an error, I get a 500 without any other details. Nothing written to the log file (even though I have error reporting on in Laravel)

# Example code

```PHP
<?php

use ZipStream\ZipStream;
use ZipStream\Option\Archive;

$options = new Archive();
$options->setSendHttpHeaders(true);
$zip = new ZipStream($filename, $options);

foreach ($files as $file) {
  /*Files is a collection of File. File model has `id`, `name` and `code`*/
  $result = $zip->addFile("project/{$file->name}", $file->code);
}
$zip->addFile("README.txt", "Readme me text here");
$zip->finish();
```

I've tried selecting files manually (by filtering them) and the error would happen for some but not for others.. it's not clear what's happening, however the problem is I'm not able to debug it, especially that the `addFile` method doesn't return anything.

Would you have a better method to debug?

# Informations

* ZipStream-PHP version: 1.2.0
* PHP version: 7.3.3

If it turns out to be an issue in the library itself, I would definitely be up to send a PR
thanks!

**Comment by NicolasCARPi** [comment]
Hello,

Normally exceptions are thrown if something goes wrong. I'll try and see if some errors are silenced when I have more time.

**Comment by jadjoubran** [comment]
Thanks for your response!
I found one here in [Stream.php](https://github.com/maennchen/ZipStream-PHP/blob/master/src/Stream.php#L126)
I'll check tomorrow if that was the issue and update this issue
Cheers

**Comment by NicolasCARPi** [comment]
@jadjoubran Did you manage to find the cause of your issue?

**Comment by jadjoubran** [comment]
Hey, thanks for checking
No, but I ended up discontinuing that feature for other reasons
