### ISSUE TITLE
rewind(): stream does not support seeking

### ISSUE THREAD

**Issue by ackerchez** [maennchen/ZipStream-PHP#132]
I am currently using this plugin for a Laravel project where I am compressing files stored on S3 and returning them to the client. 

When I try to implement this solution I am getting an exception in "DeflateStream.php" that says "rewind(): stream does not support seeking". I do not know why this is happening but it is very frustrating. Please find my code below:

                 $s3Client = S3Helper::getS3ClientInstance();
                 $s3Client->registerStreamWrapper();

                 return new StreamedResponse(function() use ($toGetFromS3, $order){
                     $zipFilename = $order->order_num.'.zip';
                     $options = new Archive();
                     //$options->setZeroHeader(false);
                     $options->setContentType('application/octet-stream');
                     $options->setSendHttpHeaders(true);
                     $options->setHttpHeaderCallback('header');

                     $zip = new ZipStream($zipFilename, $options);

                     foreach($toGetFromS3 as $typeAndItemArray){
                             $filename = $item->date->format('Y-m-d_H_i_s').'.mp3';
                             $bucket = $item->s3_bucket;
                             $key = $item->s3_key;

                             $signedUrl = S3Helper::generateAWSPreSignedUrl($bucket, $key, 10);

                             if(!($stream = fopen($signedUrl, 'r'))){
                                 dd('could not open stream for file');
                             }

                             $fileOptions = new File();
                             $fileOptions->setMethod(Method::STORE());
                             $zip->addFileFromStream($filename, $stream, $fileOptions);
                     }

                     $zip->finish();
                 });`

# Informations
* ZipStream-PHP version: 1.2
* PHP version: 7.1

I would greatly appreciate any help you can offer. 
Thanks in advance!

**Comment by ackerchez** [comment]
I find that if I uncomment the setZeroHeader, the problem does not show up...not sure if that helps.

**Comment by NicolasCARPi** [comment]
Hello,

From S3 doc:

Streams opened in "r" mode only allow data to be read from the stream, and are not seekable by default. This is so that data can be downloaded from Amazon S3 in a truly streaming manner, where previously read bytes do not need to be buffered into memory. If you need a stream to be seekable, you can pass seekable into the stream context options of a function.

See: https://github.com/maennchen/ZipStream-PHP/wiki/Symfony-example
and: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

Maybe this can help you.

**Comment by sblawrie** [comment]
I'm having trouble figuring out where to pass in the stream context with `seekable` set to true. Do I pass it in when `$s3Client` is being created (and if so, how/where?), or do I pass it in through `->getCommand()`? Sorry, seems like this should be pretty straight forward, but I couldn't find any examples of it being used with the AWS PHP SDK for Laravel wrapper. Any help much appreciated.

`
$s3Client = \App::make('aws')->createClient('s3');
        $s3Client->registerStreamWrapper();
        $response = new StreamedResponse(function () use ($Scripts, $s3Client) {
            $zip = new ZipStream('export.zip');
            foreach ($Scripts as $Script) {
                $cmd = $s3Client->getCommand('GetObject', array_merge([
                    'Bucket' => config('aws.documents_bucket'),
                    'Key' => $Script->getBucketKey(),
                ]));
                $url = (string) $s3Client->createPresignedRequest($cmd, '+1 hours')->getUri();
                $filename = str_replace(' ', '_', $Script->title);
                    $streamRead = fopen($url, 'r');
                    $zip->addFileFromStream($filename, $streamRead);
                } catch (\Exception $e) {
                    continue;
                }
            }
            $zip->finish();
        });
`

**Comment by lksnmnn** [comment]
I am currently updating from v0.5.x and getting the above error as well.
So my first question would be: 

Do I need a stream to be seekable?
How do I make a stream seekable if the files are not coming from S3?
