### ISSUE TITLE
Archive with large number of files cannot be unzipped

### ISSUE THREAD

**Issue by ackerchez** [maennchen/ZipStream-PHP#133]
I have set this up to compress a dynamic number of files into an archive. When I compress a relatively small number of files into an archive (something like 15-20 files) the download is fine. When I move up to a larger number of files (something like 300 files) I am getting an archive that is not possible to extract. I am not sure if this is a result of the ZIP dying out or something. When I looked at the error when it tried to extract, I saw "unexpected end of data, there was some data after the end of the payload data". Do you know what would cause this? 

This is a laravel installation.
* ZipStream-PHP version:   1.2
* PHP version: 7.1

**Comment by NicolasCARPi** [comment]
Yes, sounds like something timing out and stopping the process. Look into php timeout value in ini file.

**Comment by ackerchez** [comment]
Can you think of a way to catch that? It is not throwing an error when trying to grab the stream from S3 with the fopen().

Here is the code:

             $s3Client = S3Helper::getS3ClientInstance();
             $s3Client->registerStreamWrapper();
             return new StreamedResponse(function() use ($toGetFromS3, $order){
                 $zipFilename = $order->order_num.'.zip';
                 $options = new Archive();
                 $options->setZeroHeader(false);
                 $options->setContentType('application/octet-stream');
                 $options->setSendHttpHeaders(true);
                 $options->setHttpHeaderCallback('header');

                 $zip = new ZipStream($zipFilename, $options);

                 foreach($toGetFromS3 as $typeAndItemArray){
                         $filename = $item->date->format('Y-m-d_H_i_s').'.mp3';
                         $bucket = $item->s3_bucket;
                         $key = $item->s3_key;

                         $signedUrl = S3Helper::generateAWSPreSignedUrl($bucket, $key, 10);

                         if(!($stream = fopen($signedUrl, 'r'))){
                             dd('could not open stream for file');
                         }

                         $fileOptions = new File();
                         $fileOptions->setMethod(Method::STORE());
                         $zip->addFileFromStream($filename, $stream, $fileOptions);
                 }

                 $zip->finish();
             });

**Comment by NicolasCARPi** [comment]
What is the value of "max_execution_time" in ini file?

**Comment by ackerchez** [comment]
300 (seconds I assume)...

**Comment by NicolasCARPi** [comment]
Does it stop after 5 minutes?

**Comment by ackerchez** [comment]
no, much sooner than that.

**Comment by maennchen** [comment]
Based on the message „unexpected end of data, there was some data after the end of the payload data“, there‘s probably an error message at the end of your zip file. Can you take a look at the file with a text editor?

**Comment by ackerchez** [comment]
You are right, I am getting HTML at the end of the file from the generic "whoops" page. It seems that some kind of exception is not being caught. Would you know why?

**Comment by maennchen** [comment]
Not really. Look into the logs or don‘t catch the exception to see what happened...
