### ISSUE TITLE
How do you use this library in plain PHP script (without composer or other framework/library)

### ISSUE THREAD

**Issue by d-packs** [maennchen/ZipStream-PHP#134]
The title of the issue is pretty explanatory. 
I know this is not intended for questions, but maybe adding some reference to how you can accomplish this would be useful for other users too. 
Dropping a line about this in the wiki would also be great.

**Comment by d-packs** [comment]
I plan to integrate this into a Wordpress plugin and want to keep it as thin as possible, avoiding pulling a huge stack with it if possible.

**Comment by maennchen** [comment]
You can always just clone the repo and do whatever you want with it. Just be aware of the following things:

* You either need an autoloader or import everything manually.
* This is not supported by us, therefore if you experience problems we won't really support that.
* The library needs quite recent PHP versions, Wordpress will not allow that in the plugin repo if I'm not mistaken. (You'll need to use an old version which we also do not support at all anymore.)
