### ISSUE TITLE
Suggestion zeroHeader flag in File Options

### ISSUE THREAD

**Issue by Firtzberg** [maennchen/ZipStream-PHP#135]
I'm wondering if it makes sense to have the zeroHeader flag in the FileOptions rather than the Archive options.
You could keep the option in the Archive as well, to default it.

**Comment by NicolasCARPi** [comment]
Hello,

Why are you thinking about this change?

**Comment by Firtzberg** [comment]
I read the zip format specification. It appears the zero header flag is part of a file header, so it is specific to each file.

**Comment by maennchen** [comment]
Tracked via https://github.com/maennchen/ZipStream-PHP/pull/224
