### ISSUE TITLE
Download from S3 stream randomize crash file.

### ISSUE THREAD

**Issue by asika32764** [maennchen/ZipStream-PHP#137]
# Description of the problem

Below is my code. It will download some mp3 files from S3 and bundled as a zip file. however, the zip file will randomize corrupt and unable to unzip.

# Example code

The word `播放清單` in Chinese is `Playlist`

```php
<?php
set_time_limit(0);

// ...

$s3->getClient()->registerStreamWrapper();

$opt = new Archive();
$opt->setSendHttpHeaders(true);
$zip = new ZipStream(sprintf('[播放清單] %s.zip', $pl->title), $opt);

foreach ($musics as $i => $music) {
    $url = $music->stream_file;

    $url = 's3://' . $s3->getBucketName() . '/' . ltrim($url, '/');

    $context = stream_context_create(
        [
            's3' => ['seekable' => true]
        ]
    );
    $stream = fopen($url, 'r', false, $context);

    $zip->addFileFromStream(File::makeUtf8Safe($music->name) . '.mp3', $stream);
}

$zip->finish();
die;
```

# Informations

It's seems the corrupted file less some size, below 2 files are correct file, can unzip by WinRAR and MacOS Archive app.

![p-001-2020-01-07-21-39-47](https://user-images.githubusercontent.com/1639206/71899822-820e0100-3197-11ea-895d-5a39d3565296.png)

And these are corrupted files, the size also randomize less and cannot see any rule.

![p-001-2020-01-07-21-40-39](https://user-images.githubusercontent.com/1639206/71899856-9651fe00-3197-11ea-979c-7cb84e01dada.png)

Use cmd unzip it will see error message:

![p-001-2020-01-07-21-43-04](https://user-images.githubusercontent.com/1639206/71899904-abc72800-3197-11ea-8eff-3eb1657d1e60.png)

```
Archive:  [播放清單] test (4).zip
error [[播放清單] test (4).zip]:  missing 8423 bytes in zipfile
  (attempting to process anyway)
error [[播放清單] test (4).zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
  (attempting to re-compensate)
  inflating: test/[□□□□+׵ơ□ơ] □□굼□□□□ - test.pdf
  inflating: test/The First Snow.mp3
  error:  invalid compressed data to inflate
 bad CRC 343427a7  (should be ae697f7c)
file #3:  bad zipfile offset (local header sig):  2999742
  (attempting to re-compensate)
  inflating: test/Country Life.mp3
  inflating: test/Bossanova.mp3
  inflating: test/Lampasas And Pampasas.mp3

1 archive had fatal errors.
```

In this case, we can see it is `The First Snow.mp3` has invalid CRC, but the invalid file will be different in every corrupted files.

This is another files error messages:

```
Archive:  [播放清單] test.zip
error [[播放清單] test.zip]:  missing 17095 bytes in zipfile
  (attempting to process anyway)
error [[播放清單] test.zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
  (attempting to re-compensate)
  inflating: test/[□□□□+׵ơ□ơ] □□굼□□□□ - test.pdf
  inflating: test/The First Snow.mp3
  inflating: test/Country Life.mp3
  error:  invalid compressed data to inflate
 bad CRC d5f48391  (should be 8fabf29e)
file #4:  bad zipfile offset (local header sig):  5947112
  (attempting to re-compensate)
file #4:  bad zipfile offset (local header sig):  5947112
  inflating: test/Lampasas And Pampasas.mp3

1 archive had fatal errors.
```

I can make sure it won't be network issue and no-output error message caused. Seems every file downloaded from S3 will randomize less some part to make the CRC error or less zip-file size. Is there any idea about this issue?

* ZipStream-PHP version: 1.2.0
* PHP version: 7.1 7.2 7.3

**Comment by asika32764** [comment]
If I download file to local then added to ZipStream, it works.

```php
        $zip = new ZipStream(sprintf('[播放清單] %s.zip', $pl->title), $opt);

        Folder::create($tmp = WINDWALKER_TEMP . '/' . uniqid());

        foreach ($musics as $i => $music) {
            $url = MusicService::S3_STREAMING_PATH . '/' . $music->stream_file;

            $mfile = $tmp . '/' . md5(uniqid()) . '.mp3';
            $sUrl = $s3->getPreSignedUrl($url, '+20seconds');

            (new HttpClient())->download($sUrl, $mfile);

            $zip->addFileFromPath(File::makeUtf8Safe($music->name) . '.mp3', $mfile);
        }

        $zip->finish();
```

So I think it maybe ZipStream load file from S3 stream will randomize miss some file parts, but I have no idea what is the root cause.

**Comment by NicolasCARPi** [comment]
Hello,

Can you try and add the option: ` $opt->setZeroHeader(true);` ?

**Comment by asika32764** [comment]
Thank you, tested download 5 times without any error messages.

**Comment by oriongunning** [comment]
> So I think it maybe ZipStream load file from S3 stream will randomize miss some file parts, but I have no idea what is the root cause.

Yes, I have exactly the same issue. 

I've tried to use $opt->setZeroHeader(true); but I'm not quite how to trigger a download then? because it is just echoing content onto the page.

```
 foreach ($Documents as $key => $Document) {
            $s3path = "s3://".$S3Intance->bucket."/".$Document->s3Key;

            $context = stream_context_create(array(
                's3' => array(
                    'seekable' => true
                )
            ));

            if (!($stream = fopen($s3path, 'r',false,$context))) {
                die('Could not open stream for reading');
            }

            $zip->addFileFromStream($file_name, $stream);

            fclose($stream);
 }

 $zip->finish();

**Comment by NicolasCARPi** [comment]
@oriongunning you need to wrap the response, see https://github.com/maennchen/ZipStream-PHP/wiki/Symfony-example

**Comment by oriongunning** [comment]
Thanks alot @NicolasCARPi. Ok, you're right, it works if I use it with symfony. Is there any way I could do it without using symfony? I'm finding it hard to reverse engineer what the StreamedResponse class is doing.

**Comment by NicolasCARPi** [comment]
You can just use the http foundation component which includes Response objects. Or implement it yourself, or use PSR-7 streams.

**Comment by oriongunning** [comment]
Ok appreciate your help. Cheers.
