### ISSUE TITLE
Zip file inside a zip file (nested zip)

### ISSUE THREAD

**Issue by gauravmak** [maennchen/ZipStream-PHP#138]
We need to let the user download a zip file that contains:

1. A few files and
2. A zip file containing a few other files

Is this possible to implement?

Thanks.

**Comment by NicolasCARPi** [comment]
Hello,

I don't see why not, a zip file is just another regular file that you can add to your archive.

**Comment by gauravmak** [comment]
I tried adding a zip file as a stream using `addFileFromStream()` and passed another object of ZipStream but it didn't work. I will try tomorrow as a regular file, thanks.

**Comment by gauravmak** [comment]
I have been trying to make it work as a stream but no luck. Any help would be appreciated. Latest code:

```php
$tempStream = fopen('php://memory', 'r+');
$zipStreamOptions = new Archive();
$zipStreamOptions->setOutputStream($tempStream);
$insideZip = new ZipStream('inside.zip', $zipStreamOptions);
$insideZip->addFile('test.txt', 'text');
$insideZip->finish();

$zip = new ZipStream('a.zip');
$zip->addFile('main.txt', 'text');
$zip->addFileFromStream('inside.zip', $tempStream);
$zip->finish();
```

**Comment by gerritdrost** [comment]
Stumbled across this by accident. Streams have a position, all you need to do is this: 
```php
[...]
$insideZip->finish();

// Flush so we have all the data, rewind so can read it again
fflush($tempStream);
rewind($tempStream);

$zip = new ZipStream('a.zip');
[...]
```

**Comment by NicolasCARPi** [comment]
I'm glad you figured it out!

**Comment by gauravmak** [comment]
Thanks, Gerrit 👍
