### ISSUE TITLE
Fix Psalm Error

### ISSUE THREAD

**Issue by maennchen** [maennchen/ZipStream-PHP#168]
# Description of the problem

* [ ] Solve Psalm Warnings (See https://github.com/maennchen/ZipStream-PHP/runs/1350374877?check_suite_focus=true)
* [ ] Require test to pass before merging in the repository settings

**Comment by maennchen** [comment]
@NicolasCARPi Would you be able to take a look? You seem to know that tool since you set it up :)

**Comment by NicolasCARPi** [comment]
I will.
