### ISSUE TITLE
No space left on device with lambda s3

### ISSUE THREAD

**Issue by AnthonyGWeb** [maennchen/ZipStream-PHP#174]
# Description of the problem
Hi,

To begin thanks a lot for your work. I use AWS Lambda to aggregate a collection of files on one zip.
Lambda has a limitation of 512Mo in `/tmp` so I would like use a stream to zip my files collection. And store it on S3.
I have tried many manipulation without success, because I have an error with `PHP Notice:  fwrite(): Write of 269 bytes failed with errno=28 No space left on device in /var/task/vendor/guzzlehttp/psr7/src/Stream.php`.

I have seen on the S3Wrapper (register by registerStreamWrapper()) it's use `php://temp`, but I have try to open my zipFile with `a` (append) but I have the same error.

For information with less data it's work perfectly.

Have you got an idea just for append files into my zip ? 

Thanks,

# Example code
$urlCollection : List of S3 url files (~2Mo by content). (Zip attempted ~2Go)

```php
$this->client->registerStreamWrapper();

$outputContext = stream_context_create([
    's3' => ['ACL' => 'public-read'],
]);

$zipFile = fopen("s3://{my_s3_bucket}/tmp/test.zip", 'w', false, $outputContext); // I have tried to replace 'w' by 'a'

$options = new Archive();
$options->setEnableZip64(false);
$options->setZeroHeader(true);
$options->setOutputStream($zipFile);

$zip = new ZipStream(null, $options);

foreach ($urlCollection as $url) {
  if ($streamRead = fopen($url, 'r')) {
      $zip->addFileFromStream(basename($url), $streamRead);
  } else {
      var_dump('fopen error');
  }
}

$zip->finish();

fclose($zipFile);
```

# Informations

* ZipStream-PHP version: 2.1.0
* PHP version: 8.0

**Comment by korridor** [comment]
I am also using AWS Lambda (with [bref](https://github.com/brefphp/bref)) and I am experiencing the exact same problem.
I also tried this, but it did not help:

```php
$options->setFlushOutput(true);
```

@AnthonyGWeb You haven't by any chance already found a solution for it or debugged it further?


I am using the following versions:
ZipStream-PHP version: 2.1.0
PHP version: 7.4
