### ISSUE TITLE
Documentation clarificartion

### ISSUE THREAD

**Issue by pieterdt** [maennchen/ZipStream-PHP#175]
# Description of the problem

In the example for using the library with symfony (https://github.com/maennchen/ZipStream-PHP/wiki/Symfony-example) there is a note about setting the zeroheader because, if not, it might cause issues with truncated zipfiles.

Can it be clarified what kind of problems that would be? I noticed that having this set to true, results in Safari (with the default setting of auto opening safe file formats) extracts only the first file of the archive. 
In a small test setup I did, this problem is solved by setting this zeroheader to false. I'm hesitant to take on that setting because of the remark in the documentation.

# Informations

* ZipStream-PHP version:
2.1.0

**Comment by pieterdt** [comment]
in my production setup (which uses larger than the test setup), this results in archives that the are broken (they are too small; and zipinfo mentiones that there are many bytes missing).
![afbeelding](https://user-images.githubusercontent.com/756468/111638467-a2edcf80-87fa-11eb-9375-96c42422742c.png)

**Comment by maennchen** [comment]
Tracked via #224
