### ISSUE TITLE
Getting it working on php 5.4

### ISSUE THREAD

**Issue by KennySmash** [maennchen/ZipStream-PHP#187]
Not an Issue but is there any remote chance of getting this working in php 5.4?   
I know I shouldn't but we have a feature that I need to ship in a 'good enough'  
state till we are able to update our client systems?

**Comment by maennchen** [comment]
@KennySmash I do only support officially supported PHP versions.

Therefore you'll have to do this on your own.

**Comment by maennchen** [comment]
PS @KennySmash v0.4.0 was the last release supporting PHP 5.4: https://github.com/maennchen/ZipStream-PHP/blob/v0.4.0/composer.json

You can use this version. 

Please do not open any issues about bugs etc. though since this version is outdated.

**Comment by KennySmash** [comment]
@maennchen Thanks for the heads-up on the older ver, Its much appreciated. 
I don't need any support for it since its just a stop-gap till we update their php soon

**Comment by NicolasCARPi** [comment]
>  till we update their php soon

'bout time! :p
