### ISSUE TITLE
Add files in subfolder

### ISSUE THREAD

**Issue by bastien70** [maennchen/ZipStream-PHP#203]
# Description of the problem

How can I create folder and add files in ?

# Informations

* ZipStream-PHP version: 2.1.0
* PHP version: 8.0

I followed the #78 

`$zip->addFile('directory/', '');` but it doesn't create folder. Is there a method to do it ?

**Comment by maennchen** [comment]
Duplicate of #78

**Comment by ahmed-bhs** [comment]
@bastien70 did you found any solution to create an empty folder ?
