### ISSUE TITLE
UTF8 file names and comment

### ISSUE THREAD

**Issue by Afterster** [maennchen/ZipStream-PHP#22]
Hi,

Good work to continue this great little zip stream library :).

I started to move Ampache from ARCHIVES CLASSES to this and noticed an issue with utf8 filenames and comments. This is simply not supported.
I'm really not familiar with zip standard, anyway you can add utf8 support if filename/comment are utf8 strings?
Thanks!

**Comment by maennchen** [comment]
How's your research project going? :G

**Comment by donatj** [comment]
I think it used to work prior to the fix for #1 which changed the zip header to have a previous version.  I haven't dumped a ton of time on it but will continue to look into.

**Comment by Afterster** [comment]
Did you found anything @donatj?
I don't want to rush you, I'm only getting news every few months ;)
Thanks.

**Comment by maennchen** [comment]
I don't think this problem is solvable. According to the information I found the filenames are not encoded to any charset. If you have the same encoding on the source and the destination machine it works, else it won't.

http://superuser.com/questions/60379/how-can-i-create-a-zip-tgz-in-linux-such-that-windows-has-proper-filenames

@donatj: Should I close the issue or do you think you can fix this somehow?

**Comment by maennchen** [comment]
@donatj: I should read your comments first before writing. Forget about my last comment.

**Comment by rlatkn** [comment]
Hi,
i find solution for UTF-8 file names problem in another project https://github.com/barracudanetworks/ArchiveStream-php
I'm tested it, and it works.
Please, see pull request and test

**Comment by maennchen** [comment]
@rlatkn:
Thank you very much for your contribution.
Did you test if the zip can still be opened by OS X?

**Comment by rlatkn** [comment]
@maennchen 
Sorry, no, i have no possibillity

**Comment by Afterster** [comment]
Me neither... but thank you all and @rlatkn for #32.
This is an important issue for not-English countries... most of the world :smile_cat:, thank you for taking care of it. Hope to see it fixed soon.

**Comment by maennchen** [comment]
It seems to work with Mac (which is a rare thing to see with zip files...)

@rlatkn: Thanks for your work.

**Comment by Afterster** [comment]
Working as excepted, thanks :+1:
