### ISSUE TITLE
Tag v0.3.0

### ISSUE THREAD

**Issue by donatj** [maennchen/ZipStream-PHP#24]
Could we tag v0.3.0 perhaps and push further changes to a v0.4.0?  

I have a project I need this before and don't want to build against the old code base, and don't want to require an unstable release.

Besides the couple open issues that could be handled later, is there anything standing in the way of tagging it? @maennchen

**Comment by maennchen** [comment]
Hmm, I think there is nothing standing in the way.
If you do the Tag, please edit all the remeaning open issues and change the milestone to 3.1 instaed of 3.0.

Is this ok for you?

**Comment by maennchen** [comment]
I released it as v0.3.0

**Comment by donatj** [comment]
Ooh, great!  Thank you so much!

**Comment by maennchen** [comment]
Sure, I don't have time at the moment to work on this project. So a release at the current state makes sense.
PS: Have you seen the amount of installations on packagist? https://packagist.org/packages/maennchen/zipstream-php

**Comment by donatj** [comment]
I hadn't! Its pretty popular. 

I hope no ones mad about this being a breaking release.  Its pre 1.x so we're allowed to make breaking changes according to semantic versioning anyway.

**Comment by maennchen** [comment]
If we break something hopefully we get some new contributors :P 
The Version before was just old and ugly, it's time to change something.
