### ISSUE TITLE
Document default options for Zip64 & Zero Header

### ISSUE THREAD

**Issue by mkalkbrenner** [maennchen/ZipStream-PHP#267]
### ZipStream-PHP version

3.0.2

### PHP version

8.1.16

### Constraints for Bug Report

- [X] I'm using a version of ZipStream that is currently supported:
https://github.com/maennchen/ZipStream-PHP#version-support

- [X] I'm using a version of PHP that has active support:
https://www.php.net/supported-versions.php

- [X] I'm using a version of PHP that is compatible with your used
ZipStream version.

- [X] I'm using the latest release of the used ZipStream major version.

### Summary

Drupal's Search API Solr module uses zipstream to upload config-set zip files to Solr (or ZooKeeper).
It perfectly worked with 1.x and 2.x versions for years. But it doesn't work anymore with 3.0.2 or the main branch.
zipstream is not used to do HTTP, but to write a zip file to disk. This zip file then gets uploaded using https://github.com/solariumphp/solarium
The zip file itself seems to be ok and could be opened and extracted using other zip clients. But the client built into Java seems to have an issue with files created with zipstream 3.x.

### Current behavior

The issue seems to be about the file size or the size reported within the zip file:
`java.util.zip.ZipException: invalid entry size (expected 0 but got 24553 bytes)`

If I set `defaultEnableZeroHeader: false`, the error message changes, but still exists:
`java.util.zip.ZipException: invalid entry size (expected 4294967295 but got 24553 bytes)`

### How to reproduce

`drush search-api-solr:upload-configset -v --numShards=1`

### Expected behavior

The zip files produced with 2.4.0 still work. 3.0.x should be able to produce zip files that could be parsed by java.util.zip

**Comment by NicolasCARPi** [comment]
Did you set `sendHttpHeaders: false,` in the constructor? See https://maennchen.dev/ZipStream-PHP/guide/Options.html

**Comment by mkalkbrenner** [comment]
Setting `sendHttpHeaders` to true or false doesn't change anything.
As mentioned above, zipstream just generates the zip file:

```php
$file = fopen($file_name, 'w+b');
$zip = new ZipStream(outputStream: $file, defaultEnableZeroHeader: FALSE);

...

foreach ($files as $name => $content) {
      $zip->addFile($name, $content);
}

$zip->finish();

fclose($file);
```

This zip file then gets uploaded embedded into a Solr command using curl.

**Comment by maennchen** [comment]
@mkalkbrenner Sorry, you already wrote that.

Would you be able to share both a v2 and a v3 file with the same contents so we can compare?

**Comment by mkalkbrenner** [comment]
I'll prepare some files ...

**Comment by mkalkbrenner** [comment]
I can reproduce it using curl on the command line:

```
curl -X POST --header "Content-Type:application/octet-stream" --data-binary @configset_v3.0.2_zeroHeader.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=myConfigSet1"
{
  "responseHeader":{
    "status":500,
    "QTime":13},
  "error":{
    "msg":"invalid entry size (expected 0 but got 24553 bytes)",
    ...
```

```
curl -X POST --header "Content-Type:application/octet-stream" --data-binary @configset_v3.0.2.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=myConfigSet2"
{
  "responseHeader":{
    "status":500,
    "QTime":11},
  "error":{
    "msg":"invalid entry size (expected 4294967295 but got 24553 bytes)",
    ...
```

```
curl -X POST --header "Content-Type:application/octet-stream" --data-binary @configset_v2.4.0.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=myConfigSet3"
{
  "responseHeader":{
    "status":0,
    "QTime":83}}
```

**Comment by mkalkbrenner** [comment]
In order to unblock a Drupal 10.1.x compatible release of https://www.drupal.org/project/search_api_solr , can we do a 2.4.1 release including https://github.com/maennchen/ZipStream-PHP/pull/268 ?
That would also solve dependency issues for other modules at the moment, for example https://github.com/PHPOffice/PhpSpreadsheet doesn't have a v3.0.2 compatible release yet.

**Comment by maennchen** [comment]
Ok, the `v3.0.2` zip contains a `0x5653` header (`ExtendedInformationExtraField` in ZipStream), maybe solr chokes on that.

That field should only be enabled if either a UTF-8 Name, UTF-8 Comment or a Zero Header is active. Neither makes sense for your file.

```
       |                                                                             |                          |      extra_fields[0:1]:
       |                                                                             |                          |        [0]{}: extra_field
0x00034|53 56                                                                        |SV                        |          header_id: 0x5653
0x00034|      00 00                                                                  |  ..                      |          data_size: 0
       |                                                                             |                          |          data: raw bits
```

Can you try commenting out lines [183-186 in `File.php`](https://github.com/maennchen/ZipStream-PHP/blob/main/src/File.php#L183)?

**Comment by maennchen** [comment]
(for anyone trying to replicate my investigation: I'm using [`fq`](https://github.com/wader/fq) which is extremely helpful to debug binary files.)

**Comment by maennchen** [comment]
Ah, found it, should've seen that directly.

Try setting `enableZip64: false` when creating the `ZipStream` instance.

**Comment by mkalkbrenner** [comment]
`enableZip64: false, defaultEnableZeroHeader: false`

This combination made it work. Thanks for your support!

But I must admit, that this API is less intuitive as before. And it might make sense to add some hints in the migration section of the README.

**Comment by maennchen** [comment]
@mkalkbrenner One of the issues of this lib is that error handling is quite hard since 99% of the users are sending a browser reaponse and the error is just written into the zip file.

Therefore it made sense to enable Zip64 by default since it can’t be done halfway through and would result in an overflow.

Similarly, a lot of users try to stream out file contents and the zero option is what makes this efficient.

This choice should be documented properly however, both in the Migration information as well as in the API docs.

A PR for that would be very welcome.

**Comment by mkalkbrenner** [comment]
search_api_solr uses the stream functionality as well when users are downloading a Solr config-set via the user interface instead of using the drush command line tool.
Some hosters or Solr service providers offer a possibility to upload and deploy these zip files manually to their service and they deploy them. I assume that this will fail then, too.
Therefor I added `enableZip64: false, defaultEnableZeroHeader: false` to the streaming part as well.

**Comment by maennchen** [comment]
@mkalkbrenner FYI: PhpSpreadsheet just released a version compatible with v3.

**Comment by maennchen** [comment]
@mkalkbrenner On further inspection, Zip64 was already enabled in v2. The difference is that the extra headers were only used if [`zeroHeader && zip64`](https://github.com/maennchen/ZipStream-PHP/blob/v2/src/File.php#L179) while v3 was doing [`zeroHeader || zip64`](https://github.com/maennchen/ZipStream-PHP/blob/main/src/File.php#L196) and therefore added the header even if it was not needed.

Can you verify if it now works as well with #269?

Given that, I think the migration instructions (https://github.com/maennchen/ZipStream-PHP#archive-options) are clear enough and this ticket can be closed.
