### ISSUE TITLE
Pause / Resume

### ISSUE THREAD

**Issue by Eckerdecker** [maennchen/ZipStream-PHP#29]
Hello,

First of all, sorry if it's the wrong place to ask.
I would like to know if you think the ability of pause and resume a zipstream download could be a possible enhancement or if it is, by definition, impossible.

Thank you in advance for your answers.

Eckerdecker

**Comment by maennchen** [comment]
Hi,

I think it'd work only to send a partial zip. But in the Background we'll have to generate the whole zip again.
I've had a really bad experience with partial download of dynamic content in general and i wouldn't recommend it.

If you've the time to look at it yourself and want to create a pull request, I'd be happy. But I don't think tis is something I'll implement soon.

Best, Jony

**Comment by Eckerdecker** [comment]
Wow, that IS a quick answer, thank you.
As I thought it's tricky, without a regeneration of the already downloaded bytes it's impossible. Do you think the regeneration of those bytes, without serving them, would cost aproximatively the same time as if they are served?

**Comment by maennchen** [comment]
I think if you're for example targeting mobile users it could make a difference. For normal Clients I don't think you can save much resources.

**Comment by Eckerdecker** [comment]
I see, I'm not specifically targeting mobile users, i'm just thinking, and once again thank you for your lights. I will maybe think a bit more, if I come with any solution I'll let you know. Have a good day!
