### ISSUE TITLE
Option to disable UTF-8 encoding for Content-Disposition for KOBO?

### ISSUE THREAD

**Issue by mikespub** [maennchen/ZipStream-PHP#294]
### Description

I've taken over maintenance of [COPS](https://github.com/mikespub-org/seblucas-cops) and switched new releases to use ZipStream when updating metadata of EPUB books on the fly before downloading them. Overall this worked very well - thanks :-)

We're dealing with quite a range of e-book readers as clients here, all of which have their own issues and limitations with regards to browsers. Now one of them has bit us again:

apparently KOBO e-readers can't deal with UTF-8 encoded filenames for Content-Disposition - see https://github.com/mikespub-org/seblucas-cops/issues/71

From what @tobybryans tested changing this line in sendHttpHeaders() https://github.com/maennchen/ZipStream-PHP/blob/db943cf1d2ffef428d1ad1fa0b01bae475cda07c/src/ZipStream.php#L832

to use plain quotes instead of UTF-8 worked well in his case:
```
#            $disposition .= "; filename*=UTF-8''{$urlencoded}";
            $disposition .= "; filename=\"{$safeOutput}\"";
```

Is there any way this could be made configurable in ZipStream?

Thanks

**Comment by maennchen** [comment]
@mikespub You should be able to set the header yourself if you set `sendHttpHeaders: false`

**Comment by mikespub** [comment]
Yes, that was the other option I had in mind - but it never hurts to ask, right? :-)

**Comment by maennchen** [comment]
@mikespub No, of course not 😊

I‘m currently thinking that is is probably niche enough to not warrant a dedicated option.

**Comment by mikespub** [comment]
Fair enough - closing the issue here then.

**Comment by maennchen** [comment]
@mikespub I was thinking about this a bit more. I think there should be a simple way to implement this which doesn’t require a new config parameter:

Use `mb_detect_encoding` to detect if the filename is ASCII only and only set UTF-8 if it is not.

I‘d be open for a PR if you would want to give this a try.

**Comment by mikespub** [comment]
I appreciate this, but please note that according to http://test.greenbytes.de/tech/tc2231/ it's not only plain ASCII but also plain ISO-8859-1 that should be supported without UTF-8 encoding.
