### ISSUE TITLE
Unexpected end of archive - when there are more than 4 folders deep

### ISSUE THREAD

**Issue by d1ca** [maennchen/ZipStream-PHP#296]
### ZipStream-PHP version

3.0.1

### PHP version

8.1

### Constraints for Bug Report

- [X] I'm using a version of ZipStream that is currently supported:
https://github.com/maennchen/ZipStream-PHP#version-support

- [X] I'm using a version of PHP that has active support:
https://www.php.net/supported-versions.php

- [X] I'm using a version of PHP that is compatible with your used
ZipStream version.

- [X] I'm using the latest release of the used ZipStream major version.

### Summary

When trying to add file(s) to a zip and the files are at a lower level within the folders (let say 5 or more), the zip is created but it cannot be opened. you get: Unexpected end of arhive.

### Current behavior

When trying to add file(s) to a zip and the files are at a lower level within the folders (let say 5 or more), the zip is created but it cannot be opened. you get: Unexpected end of arhive.
![image](https://github.com/maennchen/ZipStream-PHP/assets/57361525/612aed2c-933b-4c58-acf7-bba7f249d6c7)

### How to reproduce

~~~php

// create a new zipstream object
$zip = new ZipStream\ZipStream(
    outputName: 'example.zip',

    // enable output of HTTP headers
    sendHttpHeaders: true,
);

// create a file named 'hello.txt'
$zip->addFile(
    fileName: 'some/other/folders/with/nothing/to/say/about/hello.txt',
    data: 'This is the contents of hello.txt',
);
 

// finish the zip stream
$zip->finish();

~~~

### Expected behavior

create the zip with unlimited number of folders and subfolders no matter of their depth in order to allow files to be at the lowest subfolders.

**Comment by d1ca** [comment]
Hi,

First of all, thanks for replying so fast.
Secondly, that's strange...
If you have time and you can, i can show you the strange behavior. It's
looks that the zip crashes when i simply make a simple function call (only
get data from DB and iterates through them).
If you can take a look, i can set up a google meeting.

Thanks,
Have a nice day

În lun., 22 ian. 2024 la 11:39, Jonatan Männchen ***@***.***>
a scris:

**Comment by maennchen** [comment]
Please test if you can open the file with other tools yourself. If it also does not work, it would be good if you could upload the file here.

I generally don't do free face to face support. If you would like to book a consulting session, you can have a look at my sponsors profile and book a session with me.

**Comment by NicolasCARPi** [comment]
I can also confirm that the issue is unreproductible, and it is likely that the unarchiver software is the culprit here.

As it turns out, much better software than WinRAR exist to deal with archives, such as the free and open source [7-zip](https://www.7-zip.org/).

**Comment by d1ca** [comment]
this is my entire code for this problem, it's a laravel app:

THE CONTROLLER
  ```
  /**
     * Downloads all files of a collection - original (or web for photos)
     * @throws OverflowException
     */
    public function download(BackBlazeService $service, string $reference, string $type = 'original'): int
    {
        abort_if(!in_array($type, ['original', 'web']), 404);
        $collection = Collection::with('descendants')->whereReference($reference)->firstOrFail();
        $allFiles= [];
        CollectionService::getFilesFromCollection($collection, $allFiles);
        $zip = CollectionService::createZip($collection->name);

        foreach ($allFiles as $data) {
            $file = $data['file'];
            $name = $data['name'];
            if ($file['backblaze_id']) {
                if ($type === 'web' && $file['type'] === EnumFileType::IMAGE) {
                    if (Storage::disk('public')->exists('hd/'.$file['path'])) {
                        $zip->addFile($name, Storage::disk('public')->get('hd/'.$file['path']));
                    }
                } else {
                    $zip->addFile($name, $service->get($file['backblaze_id']));
                }
            }
        }

        return $zip->finish();
    }

```

COLLECTION SERVICE
```
    /**
     * @param  Collection  $collection
     * @param  array  $allFiles
     * @param  string  $prefix
     * @return void
     */
    public static function getFilesFromCollection(Collection $collection, array &$allFiles = [], string $prefix = ''): void
    {
        if ($collection->files()->count()) {
            $files = $collection->files()->visible()->select('type', 'path', 'name', 'extension', 'backblaze_id')->get();
            foreach ($files as $file) {
                $filename = $prefix.$file->name.'.'.$file->extension;
                $allFiles[] = [
                    'name' => $filename,
                    'file' => $file->toArray()
                ];
            }
        }
        $subcollections = $collection->children;
        foreach ($subcollections as $children) {
            self::getFilesFromCollection($children, $allFiles, $prefix.$children->name.'/',);
        }
    }
```

note:
- everything goes well till the recursive part it is called
- if i comment last foreach, the zip its fine, if not, i get the error
- there are not a lot of files/data in db so it is not a memory problem
- if i just dump the data into an array and then use that array to create the zip, it works fine

**Comment by d1ca** [comment]
this is my entire code for this problem, it's a laravel app:

THE CONTROLLER
  ```
  /**
     * Downloads all files of a collection - original (or web for photos)
     * @throws OverflowException
     */
    public function download(BackBlazeService $service, string $reference, string $type = 'original'): int
    {
        abort_if(!in_array($type, ['original', 'web']), 404);
        $collection = Collection::with('descendants')->whereReference($reference)->firstOrFail();
        $allFiles= [];
        CollectionService::getFilesFromCollection($collection, $allFiles);
        $zip = CollectionService::createZip($collection->name);

        foreach ($allFiles as $data) {
            $file = $data['file'];
            $name = $data['name'];
            if ($file['backblaze_id']) {
                if ($type === 'web' && $file['type'] === EnumFileType::IMAGE) {
                    if (Storage::disk('public')->exists('hd/'.$file['path'])) {
                        $zip->addFile($name, Storage::disk('public')->get('hd/'.$file['path']));
                    }
                } else {
                    $zip->addFile($name, $service->get($file['backblaze_id']));
                }
            }
        }

        return $zip->finish();
    }

```

COLLECTION SERVICE
```
    /**
     * @param  Collection  $collection
     * @param  array  $allFiles
     * @param  string  $prefix
     * @return void
     */
    public static function getFilesFromCollection(Collection $collection, array &$allFiles = [], string $prefix = ''): void
    {
        if ($collection->files()->count()) {
            $files = $collection->files()->visible()->select('type', 'path', 'name', 'extension', 'backblaze_id')->get();
            foreach ($files as $file) {
                $filename = $prefix.$file->name.'.'.$file->extension;
                $allFiles[] = [
                    'name' => $filename,
                    'file' => $file->toArray()
                ];
            }
        }
        $subcollections = $collection->children;
        foreach ($subcollections as $children) {
            self::getFilesFromCollection($children, $allFiles, $prefix.$children->name.'/',);
        }
    }
```

note:
- everything goes well till the recusivity it is called
- if i comment

**Comment by d1ca** [comment]
note:

- everything goes well till the recursive part it is called
- if i comment the last foreach everything works as expected, otherwise it fails
- if a just dump all data into an array and then use that array (different request) the zip is created with success, but it fails if its in same request

**Comment by maennchen** [comment]
I see no obvious error on a first glance. Please try to open the file with another unarchiving tool to see if it works. If not, please share a file here so that we can see what is wrong with the generated file.

**Comment by d1ca** [comment]
[Cristiano Ronaldo (2).zip](https://github.com/maennchen/ZipStream-PHP/files/14012088/Cristiano.Ronaldo.2.zip)
This is a zip arhive with issue
i've tried to open it also with WinZip Universal (windows 10) and i get same result

**Comment by NicolasCARPi** [comment]
If you use `less` to look at the zip file, you can see that debug code is added to the archive at the end:

![2024-01-22-163747_917x295_scrot](https://github.com/maennchen/ZipStream-PHP/assets/3043706/532acb5d-0632-4568-97be-f7f04e0ad9a0)

I am not quite sure what exactly is the issue but now you have a full stack trace to help you debug ;) (might be best to not stream the zip but let the error happen so you can catch it with normal debug window)

**Comment by d1ca** [comment]
thank you, i guess it's not a bug :)
