### ISSUE TITLE
Large file support

### ISSUE THREAD

**Issue by filerun** [maennchen/ZipStream-PHP#30]
There are other similar libraries with support for Zip64, to allow files larger than 2GB to be zipped. It would be great if you could add that to this library as well. Great work, btw!

**Comment by donatj** [comment]
Could you provide some examples?

**Comment by vvllaadd** [comment]
https://github.com/barracudanetworks/ArchiveStream-php

**Comment by donatj** [comment]
Huh, we branched off the same library. That's interesting.  I'll look into this, thanks!

**Comment by mattvot** [comment]
Any update on supporting Zip64? Cheers

**Comment by maennchen** [comment]
Hmmm...
@donatj Should we maybe think about partnering up with the ArchiveStream guys? It looks like they did a really good job on improving the lib.
