### ISSUE TITLE
`OperationMode::SIMULATE_STRICT` and zero-byte files

### ISSUE THREAD

**Issue by tomwelch** [maennchen/ZipStream-PHP#301]
### ZipStream-PHP version

3.1.0

### PHP version

8.3.3

### Constraints for Bug Report

- [X] I'm using a version of ZipStream that is currently supported:
https://github.com/maennchen/ZipStream-PHP#version-support

- [X] I'm using a version of PHP that has active support:
https://www.php.net/supported-versions.php

- [X] I'm using a version of PHP that is compatible with your used
ZipStream version.

- [X] I'm using the latest release of the used ZipStream major version.

### Summary

I'm using the SIMULATE_STRICT Operation Mode to add the Content-Length header as documented [here](https://maennchen.dev/ZipStream-PHP/guide/ContentLength.html) but I'm running into an error with zero-byte files (think .gitkeep etc)

### Current behavior

A SimulationFileUnknownException is thrown when calling addFileFromCallback() and the exactSize is 0.

### How to reproduce

Set the Operation Mode to SIMULATE_STRICT and add a file that has a size of zero bytes.

```php
$files = [
    'hello-world.txt', // content: "hello world"
    'empty-file.txt',  // content: ""
];

$zip = new ZipStream(
    operationMode: OperationMode::SIMULATE_STRICT,
    defaultCompressionMethod: CompressionMethod::STORE,
    outputName: 'archive.zip',
);

foreach ($files as $path) {
    $zip->addFileFromCallback(
        fileName: basename($path),
        callback: fn () => fopen($path, 'r'),
        exactSize: filesize($path),
    );
}

$zip->finish();
```

### Expected behavior

(Hopefully) it is possible to use the SIMULATE_STRICT Operation Mode with empty files.

**Comment by maennchen** [comment]
@tomwelch Can you try if #302 fixes your issue?

**Comment by maennchen** [comment]
Closing in favor of PR

**Comment by tomwelch** [comment]
Good morning @maennchen. That looks great, thank you for the fix!
