### ISSUE TITLE
Creating CRC fails on 32-bit system due to too small integers

### ISSUE THREAD

**Issue by lairg99** [maennchen/ZipStream-PHP#303]
### ZipStream-PHP version

3.1.0

### PHP version

8.1.27

### Constraints for Bug Report

- [X] I'm using a version of ZipStream that is currently supported:
https://github.com/maennchen/ZipStream-PHP#version-support

- [X] I'm using a version of PHP that has active support:
https://www.php.net/supported-versions.php

- [X] I'm using a version of PHP that is compatible with your used
ZipStream version.

- [X] I'm using the latest release of the used ZipStream major version.

### Summary

Line 359 in `File` creates a CRC by using the `hexdec` function and is expecting an integer. But on 32-bit systems a float can be returned, so that the type  isn't compatible. 

For example, the hash `hexdec('b2449247')` cannot be stored as integer which leads to an exception.

> Cannot assign float to property ZipStream\File::$crc of type int

When trying to cast it explicitly, it will generate a negative integer.

```php
(int) hexdec('b2449247') // -1304128953
```

### Current behavior

Instead of an integer a float should be used.

### How to reproduce

Use the hash `b2449247` and throw it into `hexdec`.

### Expected behavior

In case of `b2449247` the float value 2990838343.0 should be assigned to `crc`.

**Comment by maennchen** [comment]
@lairg99 ZipStream v3 only supports 64bit PHP as stated in the `composer.json`:

https://github.com/maennchen/ZipStream-PHP/blob/a8b410f5673ab97b5c78461170b427c3908d528e/composer.json#L25

Consider upgrading to 64 bit or alternatively use an older version (v2) supporting 32 bit architectures.
