### ISSUE TITLE
addFileFromStream is not working for stream read from s3 

### ISSUE THREAD

**Issue by itsismail** [maennchen/ZipStream-PHP#31]
Hi 

I am reading a stream from S3 & trying to add that stream to zip but it does not work. It create empty zip file. Below is sample code.

``` php
require_once './vendor/autoload.php';
use Aws\S3\S3Client;
use ZipStream\ZipStream;

$client = S3Client::factory(array(
     'region' => 'us-east-1',
    'version' => 'latest',
    'credentials' => array(
    'key' => 'key',
    'secret'  => 'skey',
   )
));

$client->registerStreamWrapper();
$bucket = 'test-files';
$key = 'ab76d9d.mpg';
$context = stream_context_create(array(
    's3' => array(
        'seekable' => true
    )
));

if (!($stream = fopen("s3://{$bucket}/{$key}", 'r',false,$context))) {
    die('Could not open stream for reading');
}

$zip = new ZipStream('example.zip');
$zip->addFileFromStream('goodbye.mpg', $stream);
fclose($fp);
$zip->finish();
```

**Comment by donatj** [comment]
Hmm - that is a really interesting use case I had never considered. Give me a few minutes and I'll poke this as I'm conveniently working with S3 right now.

It's probably worth noting that if you're using this for compression, streams are only added with STORE so there is no compression. It's useful for grouping multiple files, but not for compressing.

**Comment by donatj** [comment]
The good news is that it *is* grabbing the content, the bad news is the manifest is coming out different and broken for some reason. Still investigating.

**Comment by donatj** [comment]
The CRC comes out exactly the same from S3 and local... hmm...

**Comment by donatj** [comment]
AHA, I think I figured it out.  There might be a small bug in the AWS S3 SDK stream wrapper. 

We calculate the file size by seeking to the end of the stream and getting the position, ala:

```php
fseek($stream, 0, SEEK_END);
$zlen = $len = ftell($stream);
```

The problem appears to be this is getting us one less than the actual size.  I am going to boil this down and open an s3 ticket.

**Comment by donatj** [comment]
I have opened an issue https://github.com/aws/aws-sdk-php/issues/809 on the S3 SDK about the issue.

**Comment by itsismail** [comment]
That's great, I was able to create zip but that was corrupted one. Also you are right I am trying to group mutiple files in single zip & present user the link.

One more thing while working in java I have opened a stream from s3 & starting writing it to response output stream, so in this fashion downloading for zip is started as soon as the stream ilbegin to write on output stream, mean user does not have to wait. My question is can we achieve same  behavior with php? ( as i do not have much hands on with php)

**Comment by donatj** [comment]
If you check the AWS ticket they fixed it in Guzzle, so you should be able to fix it with a composer update of Guzzle. Closing the ticket.

**Comment by jbruni** [comment]
Hey... I'm facing exactly the same issue. I will try to grab more information.

**Comment by jbruni** [comment]
Hey @maennchen - thanks a lot for maintaining this very useful library.

Issue resolved here.

Something weird happened that PHP was not getting the changes I was doing to my code. I had to restart the VM, and after the restart, the code I already had simply worked. The zip contains all the files, as it should.

So, for me, the problem was unrelated ZipStream-PHP, and this issue can remain closed. Sorry for the false alert.

**Comment by maennchen** [comment]
@jbruni Great, no problem ;)

**Comment by donatj** [comment]
@jbruni I've seen similar things happen when opcache was turned on, might be worth investigating
