### ISSUE TITLE
support concurrent requests

### ISSUE THREAD

**Issue by langziyang** [maennchen/ZipStream-PHP#318]
### Description

i use symfony httpclient download file to local and zip it, 
if i use concurrent requests,the download will be fast than zipstream
```php
$responses = [];
for ($i = 0; $i < 379; ++$i) {
    $uri = "https://http2.akamai.com/demo/tile-$i.png";
    $responses[] = $client->request('GET', $uri);
}

foreach ($responses as $response) {
    $content = $response->getContent();
    // ...
}
```

**Comment by maennchen** [comment]
@langziyang Zipstreams main focus is to only use the minimum amount of memory. We do this by only reading information, when it is required to be written and don’t keep it around for longer. We use streams extensively to do this.

This is essentially the opposite of trying to do things concurrently where data needs to be buffered.

This is not something I plan to support in the library therefore. I would recommend you to implement your own logic and preload the files before you write them to a zip file.

Zipstream allows you to add data from various types of sources (files, memory, php resources like pointers and streams). That should provide the flexibility you require.
