### ISSUE TITLE
Problem with PHP Memory Usage in zipStream Download

### ISSUE THREAD

**Issue by secretj** [maennchen/ZipStream-PHP#321]
### ZipStream-PHP version
2.2.6

### PHP version
7.4

### Description
While implementing the entire file download through streaming using addFileFromStream, there was a phenomenon where php memory was insufficient.

The cause was that the zip file was created through streaming, but when it was sent to the client, a large amount was sent at once, so php memory was full.
I searched a lot to solve this, but I couldn't find a clear answer.
(Most of them said to release the php memory limit, but I don't think this is a fundamental solution. Eventually, the memory will be exceeded when the zip size increases.)
The way I solved it was to create a zip and send it, and to send the response through the send() of StreamedResponse of the "sunra/php-simple-html-dom-parser": "1.5.2" library.
Is there a function like this already provided in zipStream?

### Example Code
```php
   $response = new StreamedResponse(function() use($attachments) {
            $zip = new Zip();

            foreach($attachments as $attachment){
                if ($attachment->getDeldate() != 0) {
                    continue;
                }
                $foldername = $attachment->getFolderName();
                $filename = $attachment->getAttachmentFilename();
                $fileUrl = makeFileUrl('bbs', $foldername, SERVICEID);
                // addFileFromStream call
                $zip->addStreamFile($filename, $fileUrl);
            }
            $zip->finish();
        });
        ob_end_clean();
	$response->send();
```

**Comment by maennchen** [comment]
@secretj Version 2.2.6 is only receiving security fixes at this point. Update to version 3 for a supported version.
