### ISSUE TITLE
How tu use addFileFromStream() with 'fopen' on a remote url?

### ISSUE THREAD

**Issue by leftdevel** [maennchen/ZipStream-PHP#35]
Hi there.

I'm trying to use `fopen` to read an image from a remote url, and read the content in chunks. I need it to be in chunks since the file can be very large, and the memory limitation wouldn't let me load the full image in one go.

I've tried to use 'addFileFromStream()' method. But this part of the code doesn't work:

```
    // calculate header attributes
    fseek($stream, 0, SEEK_END);
```

`fseek` doesn't work with fopen on a remote url:

```
Warning: fseek(): stream does not support seeking in ZipStream.php on line 337
```

Long story short, this is how I'd need the code to work:

```
$zip = new ZipStream('mybundle.zip');
$fh = fopen('https://pixabay.com/static/uploads/photo/2016/07/10/21/47/cat-1508613_960_720.jpg');

$chunkSize  = 1048576; // 1MB.
while(!feof($fh)) {
    $data = fread($fh, $chunkSize);
    $zip->send($data);
}
$zip->finish();
exit(0);
```
Is there anyway I can achieve this with ZipStream? Thank you.

**Comment by maennchen** [comment]
The fseek is needed to get the file length, which is needed for the zip file header. Do you have the possibility to find out the file size in another way?

You could make a PR which gives the method an optional argument length. In your case you could provide it manually and skip the fseek.

**Comment by maennchen** [comment]
Also the argument could be mandatory is this code returns false:

```php
function is_seekable($stream) {
  $meta = stream_get_meta_data($stream);
  return $meta['seekable'];
}
```

**Comment by donatj** [comment]
You may be able to get the size of the download from a HEAD request if the server is well behaved.

@maennchen I like the optional size param and definitely think we should add it, we could consider adding an addFromUrl as well, maybe not, just a thought.

**Comment by maennchen** [comment]
I'm currently thinking of refactoring the whole library anyways that new types of file sources could be implemented by adding a class that implement some interface.

For now I think the optional parameter is sufficient.

**Comment by maennchen** [comment]
Actually the proposed solution will not work. We also need to rewind the file pointer to calculate the crc32 hash. I see no possibility to handle unseekable streams.

**Comment by maennchen** [comment]
(Without providing the crc32 hash & the length)

**Comment by leftdevel** [comment]
I got a fully working solution. I'll submit a PR for reviewal and feedback in some hours.

**Comment by donatj** [comment]
@leftdevel I'll be very interested to see it.  I can't imagine how you'd have the crc32 hash calculated in time for the ZIP header without caching the entire stream somewhere first.

**Comment by leftdevel** [comment]
Done. I've sent a PR #39
