### ISSUE TITLE
PHP core ZipArchive versus ZipStream-PHP

### ISSUE THREAD

**Issue by sukhjindersingh** [maennchen/ZipStream-PHP#40]
I am checking good solutions for zipping stream content from S3, I came across to this API, however there is core PHP class [ZipArchive](http://php.net/manual/en/class.ziparchive.php), and with the help of ZipArchive::addFromString[http://php.net/manual/en/ziparchive.addfromstring.php](url), we can achieve the same. 

My query is in what respect this API is different then ZipArchive?

**Comment by maennchen** [comment]
The ZipArchive can only generate Zip Files which you can then send to the browser. This library also streams the output to the browser. This way you don't have to generate a local file and wait until the zip is finished before you send it.

**Comment by sukhjindersingh** [comment]
Thanks a lot @maennchen for replying to my query. I am bit confused. Let me try to give one example and then I will seek your advice about it. Below the first code is with the help of ZipArchive and second one with ZipStream-PHP

**ZipArchive**
```
$s3 = amazons3\S3Client::factory(); 
$phpForceDownload[]= 's3://my-bucket/image1.jpeg';
$phpForceDownload[]= 's3://my-bucket/image2.jpeg';
$zip = new ZipArchive();
$tmp_file = tempnam('.','');
 $zipName = $tmp_file.'.zip';
 $zip->open($tmp_file, ZipArchive::CREATE);
 foreach($phpForceDownload as $fileUrl){                 
          $file = $s3->getObject(array(
              'Bucket' => 'my-bucket',
              'Key'    => $fileUrl
));        
 $bodyAsString = (string) $file['Body'];        
 $zip->addFromString(basename($fileUrl),$bodyAsString); 
}

$zip->close();
header('Content-disposition: attachment; filename='.$zipName);
header('Content-type: application/zip');
readfile($tmp_file);
```
**ZipStream-PHP**

```
$s3 = amazons3\S3Client::factory();
$phpForceDownload[]= 's3://my-bucket/image1.jpeg';
$phpForceDownload[]= 's3://my-bucket/image2.jpeg';

# Autoload the dependencies
require 'vendor/autoload.php';

$zip = new ZipStream\ZipStream('example.zip');

foreach($phpForceDownload as $file){
  // We need to use a command to get a request for the S3 object
  //  and then we can get the presigned URL.
  $command = $this->s3Client->getCommand('GetObject', array(
    'Bucket' => 'my-bucket',
    'Key' => $file
  ));
  $signedUrl = $command->createPresignedUrl();

  // Get the file name on S3 so we can save it to the zip file
  //  using the same name.
  $fileName = basename($file);


  // We want to fetch the file to a file pointer so we create it here
  //  and create a curl request and store the response into the file
  //  pointer.
  // After we've fetched the file we add the file to the zip file using
  //  the file pointer and then we close the curl request and the file
  //  pointer.
  // Closing the file pointer removes the file.
  $fp = tmpfile();
  $ch = curl_init($signedUrl);
  curl_setopt($ch, CURLOPT_TIMEOUT, 120);
  curl_setopt($ch, CURLOPT_FILE, $fp);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
  curl_exec($ch);
  curl_close($ch);
  $zip->addFileFromStream($fileName, $fp);
  fclose($fp);

}

// Finalize the zip file.
$zip->finish();
```
**ZipArchive**
As per your comments ZipArchive will firstly download the content fromt S3 to server then send it to the browser? However ZipStream-PHP will not download but stream S3 directly and zip it and send it to the browser?

Secondly
**ZipStream-PHP**
Do I have add the header as I did with ZipArchive, if I have to provide url for download or user clicked on download button?

**Comment by maennchen** [comment]
With ZipArchive you will do the following:
1. Create ZIP Tempfile
2. Download File from S3
3. Put Downloaded File into ZIP Tempfile
4. Send Tempfile to Browser

This way the browser will start to get data at step 4.

This ZipStream you will have no tempfiles. Also the browser will start to receive data very fast (since it doesn't wait until the zip is finished).

The headers will be set by ZipStream.

If you want to see the difference, try to download a massive file. The browser will start downloading much sooner with ZipStream.

**Comment by sukhjindersingh** [comment]
Thanks a lot @maennchen for detailed explanation, much appreciated.

**Comment by maennchen** [comment]
Sure, no problem.
