### ISSUE TITLE
Support for dub directories within the zip stream?

### ISSUE THREAD

**Issue by mkalkbrenner** [maennchen/ZipStream-PHP#42]
Are there any plans to support that?

**Comment by maennchen** [comment]
Hi @mkalkbrenner

Sub Directories are supported.

Code:
```php
<?php
declare(strict_types = 1);
require 'vendor/autoload.php';

$zip = new \ZipStream\ZipStream('example.zip');
$zip->addFile('example/test1/hello.txt', 'Test Content');
$zip->addFile('example/test2/hello.txt', 'Test Content');
$zip->finish();
```

Result:
![screen shot 2016-09-13 at 10 06 57](https://cloud.githubusercontent.com/assets/333918/18469988/f40ef67e-7999-11e6-8563-d3b4c4521eaf.png)

**Comment by mkalkbrenner** [comment]
Thanks for your reply. That's exactly how I tried it. But for some reason it didn't work.
But now I know that it should work and I'll do some debugging.

**Comment by maennchen** [comment]
No Problem. Let me know if you find a bug.

**Comment by tomschlick** [comment]
@maennchen did you ever figure out what your bug was? I'm having the same problem where files without a subdirectory download fine, but the same file in a subdirectory produces an unextractable zip file.

**Comment by tomschlick** [comment]
Sorry meant to mention @mkalkbrenner on that one

**Comment by donatj** [comment]
@tomschlick / @mkalkbrenner What tool are you using to extract the zips out of curiosity and on what OS?

**Comment by tomschlick** [comment]
It turned out not to be directly zip related but related to the library sending out headers multiple times (which causes an error and kills the stream). 

I haven't tracked down exactly where it was doing it, but I added a workaround by  inserting an empty closure to suppress the headers and am sending them manually

```php
$zip = new ZipStream("{$folder->id} - {$folder->name}.zip", [
    'http_header_callback' => function ($name) {
    },
]);
```

**Comment by mkalkbrenner** [comment]
I'm using MacOS and didn't find a solution so far. At the moment I simply don't create directories to avoid the issue.

**Comment by donatj** [comment]
@tomschlick Sounds to me like you might have an echo or some accidental whitespace or something somewhere in your code before using ZipStream.

A common accidental cause of this can be having whitespace after a closing tag on an include, eg:

```php
<?php
//…
?>


```

There is a setting where I believe php will remove one final whitespace character, I'm not sure if that's enabled by default. I stopped including closing tags a long time ago.
