### ISSUE TITLE
Fix release "v.0.4.0". It should be "v0.4.0"

### ISSUE THREAD

**Issue by leftdevel** [maennchen/ZipStream-PHP#44]
Hi there. Seems composer can't parse "v.0.4.0". (notice the "." after the "v").
I noticed you have a newer release "v0.4.1", but I can't use it because we still are on PHP 5.5; and that release enforces php 5.6 >=

Can you please create a "v0.4.0" release? It should point to 
b1fad778ef53873cb79ed7998a6515a967955746

Thanks!

**Comment by maennchen** [comment]
Hey,
Sorry about that. It should be fixed now.

**Comment by leftdevel** [comment]
No worries, thank you a lot!
