### ISSUE TITLE
Corrupt File

### ISSUE THREAD

**Issue by tillkruss** [maennchen/ZipStream-PHP#45]
I've copied the sample code from https://github.com/maennchen/ZipStream-PHP/issues/31 and get a corrupt zip archive on macOS using PHP 7.1.

I've also tested the code here from https://github.com/aws/aws-sdk-php/issues/809 and get matching bytes length.

**Comment by maennchen** [comment]
@tillkruss Is your question answered with the comments from #36 ?

**Comment by tillkruss** [comment]
Yes!
