### ISSUE TITLE
How to use this lib with folder path

### ISSUE THREAD

**Issue by sagar3506** [maennchen/ZipStream-PHP#47]
i am sorry for this question but i found it is very useful lib for my school project but i  really don`t know how to use this lib.

can anyone give me step by step instruction with folder zip to download in stream without store to local storage. 

it will be very helpful if i get working zip file using this lib.

**Comment by maennchen** [comment]
Hey @sagar3506,

I'd love to help you out. Do you know how to use composer?

Step By Step Guide:
* [Install Composer](https://getcomposer.org/download/)
* `$ composer init` in your project
* `$ composer require "maennchen/zipstream-php"`
* Create a PHP File like the one in the [README](https://github.com/maennchen/ZipStream-PHP/blob/master/README.md#overview).

Basically after you created an instance of `ZipStream`, you can call those methods on your instance:

* `addFile($fileNameInZip, $contents)` - `$contents` is a string containing the file contents
* `addFileFromPath($fileNameInZip, $filePathOnYourDisk)` - `$filePathOnYourDisk` is a string pointing to a file on your disk
* `addFileFromStream($fileNameInZip, $stream)` - `$stream` has to contain a PHP stream. you can get those from various places like [`fopen`](http://php.net/manual/en/function.fopen.php) or [`curl`](http://php.net/manual/en/ref.curl.php)

Don't forget to call `finish` when all of the files are added to the zip.

**Comment by sagar3506** [comment]
Thank you sir its very helpful at 1st level

**Comment by sagar3506** [comment]
How to zip a folder with all file using this lib ?

**Comment by maennchen** [comment]
You have to do that manually.

See this to see how to iterate all files in a directory:
http://stackoverflow.com/questions/4202175/php-script-to-loop-through-all-of-the-files-in-a-directory

**Comment by sagar3506** [comment]
<?php

require 'vendor/autoload.php';


$zip = new ZipStream\ZipStream('123.zip');

$path = "sagar/";

$dir = new DirectoryIterator($path);

foreach ($dir as $fileinfo) {
    if (!$fileinfo->isDot()) {
          $filePath = $fileinfo->getPathname();
		  if(!is_dir($filePath)) {
			  
			$zip->addFileFromPath(substr($filePath, $pathLen + 1), $filePath);

		  }
	}
}

$zip->finish();



?>

**Comment by sagar3506** [comment]
it is correct ?

**Comment by maennchen** [comment]
It looks correct. How is the zip damaged?

(Try to unzip via the command line. You'll see the error.)

You can also try to look into the zip with a text editor to make sure that you have no warnings / errors. If you had warnings, it'd corrupt the zip.

**Comment by sagar3506** [comment]
in text editor its give blank in notepad++

**Comment by maennchen** [comment]
Can you print the file paths to make sure it adds the correct files?

**Comment by maennchen** [comment]
@sagar3506 Did you solve the issue? Can I close this?

**Comment by sagar3506** [comment]
sorry for late replay but i dont solve the every time its give damage zip

**Comment by maennchen** [comment]
Closing because no further information was given.
