### ISSUE TITLE
$zip->addFile immediatly returns a response

### ISSUE THREAD

**Issue by nexana** [maennchen/ZipStream-PHP#48]
Calling the addFile method immediatly retuns an HTTP response resulting in in invalid ZIP file.

I've executed the code that was provided in the readme: 

`$zip->addFile('hello.txt', 'This is the contents of hello.txt');`

Version used : 0.4.1 and 0.3.1 
Apache/2.4.17 (Win32) OpenSSL/1.0.2d
PHP/5.6.21

**Comment by maennchen** [comment]
The methods are supposed to stream outputs to the browser. Did you get a warning / error written to the browser? (Look into the zip file with a text-editor.)

**Comment by nexana** [comment]
@maennchen It's possible that I wrongly interpreted the working of the package. I assumed the zipfile was built as an IO stream, not directly streamed a response to the browser.

I ended up using a different technique for that purpose.
