### ISSUE TITLE
How to stream ZIP to aws s3

### ISSUE THREAD

**Issue by polantis** [maennchen/ZipStream-PHP#51]
Hello,

I would like to create large zips on my instances and send it back to S3 to store them. However zipStream does not heritate from file so i don't know how to send it back.

Is there anyway?

Thanks

**Comment by maennchen** [comment]
It should be possible to give the option output_stream to the constructor containing a file pointer.
Can you check if this solves your problem?

**Comment by polantis** [comment]
I am not sure if i have understood but a file object needs a path and i cannot get it before generating the zip.
`$opt = array(
                'comment' => "test",
                'content_type' => 'application/octet-stream',
                'output_stream' => new File("test/test.zip")
            );`

**Comment by maennchen** [comment]
The point of this library is to stream the contents of the zup file. If you do not know the destination, that's missing the point.
You habe to pass a file pointer (eg. fopen) to the constructor.

**Comment by polantis** [comment]
Sorry i had misunderstood the "file pointer" and thank you it is working with output_stream to S3
