### ISSUE TITLE
how to download the zipstream from brower and the limit size

### ISSUE THREAD

**Issue by shouhouhuakai** [maennchen/ZipStream-PHP#52]
well，the zipstream is very useful for my project and I wonder how to get the zipstream from a http request? and I wonder is there a limit size for zipstream? I test the zipstream but I can only get zip under 10MB.

**Comment by maennchen** [comment]
You can add a file from a pointer to the zip. This can for example be achieved using curls option CURLOPT_FILE.

There should be no size limit. I managed to add gigabytes of files to the zip.

**Comment by shouhouhuakai** [comment]
thanks a lot! and I will try this

**Comment by shouhouhuakai** [comment]
function curlDownload(){

    $zip = new \ZipStream\ZipStream("hi.zip");

    # add a lot of http urls
    $fileurls = array('http://img31.mtime.cn/pi/2014/10/22/092931.12614666_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.79193700_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.83594133_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.15132157_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.23093159_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.32430903_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.54820357_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.67812216_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.82617640_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092931.63431992_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092930.21198509_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092930.27969265_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092930.96611339_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092930.20711787_1000X1000.jpg', 'http://img31.mtime.cn/pi/2014/10/22/092930.54944348_1000X1000.jpg', 'http://img31.mtime.cn/pi/2015/02/23/155112.27271628_1000X1000.jpg', 'http://img31.mtime.cn/pi/2015/02/23/155113.85221579_1000X1000.jpg', 'http://img31.mtime.cn/pi/2015/02/23/155123.57198144_1000X1000.jpg', 'http://img31.mtime.cn/pi/2015/02/23/155133.54326091_1000X1000.jpg', 'http://img31.mtime.cn/pi/2015/02/23/155122.56785311_1000X1000.jpg', 'http://img31.mtime.cn/pi/2015/02/23/155121.63000981_1000X1000.jpg', 'http://img31.mtime.cn/pi/2015/02/23/155123.71640313_1000X1000.jpg');


    $fileurlslen = count($fileurls);


    for ($x = 0; $x < $fileurlslen; $x++) {
        $fp = tmpfile();

        
        $ch = curl_init('localhost:63342/PhpFirstProject/test.zip');

       
        curl_setopt($ch, CURLOPT_FILE, $fp);
        
        curl_exec ($ch);
        
        curl_close ($ch);

        $zip->addFileFromStream($fileurls[$x], $fp);
        fclose($fp);
    }

    $zip->finish();
}

hi,above is my code,but it doesn't work well, what I want to do is put many download urls to a zipstream and I can download the zip from the brower. I'm new in php and look forward for your help,thanks

**Comment by maennchen** [comment]
Working Example:

```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use ZipStream\ZipStream;

// Create new Zip
$zip = new ZipStream("hi.zip");

// add a lot of http urls
$urls = [
  'http://img31.mtime.cn/pi/2014/10/22/092931.12614666_1000X1000.jpg',
  'http://img31.mtime.cn/pi/2014/10/22/092931.79193700_1000X1000.jpg',
];

foreach($urls as $url) {
  // Create Temp File
  $fp = tmpfile();

  // Download File
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_FILE, $fp);
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_exec($ch);

  // Force to write all data
  fflush($fp);

  // Rewind to the beginning, otherwise the stream is at the end from the start
  rewind($fp);

  // Find out a file name from url
  // In this case URL http://img31.mtime.cn/pi/2014/10/22/092931.12614666_1000X1000.jpg will yield
  // /pi/2014/10/22/092931.12614666_1000X1000.jpg as file path
  $filename = parse_url($url, PHP_URL_PATH);

  // Add File
  $zip->addFileFromStream($filename, $fp);

  // Close the Temp File
  fclose($fp);
}

// Finish ZIP
$zip->finish();

```

I currently do not have the time for further PHP support. Please get help at a forum / chat etc. for further questions.

**Comment by shouhouhuakai** [comment]
thank you very much, I know you are very busy and I have asked the same question in stackoverflow. Don't answer me until you are free. I have tried your code and when the urls are small,it works very well,but when the urls are bigger(maybe 50 or more), my browser turns around and around and I can't get the zip, when you tried to add gigabytes of files to the zip, can you get the zip from the browser successfully？

**Comment by shouhouhuakai** [comment]
hi,maennchen,thanks a lot for your working example and it works well. I don't want to bother you and please answer me when you free.  I found a very interesting thing. I run the example using PhpStorm (no matter Xdebug mode or not) and my server is apache. I found that when the network is unreachable and connected again, the zip file can again be downloaded,it means that the zip continued to download when the network changed. It's very amazing,because in my point of view, it's a http request and can't locate the url when I connected to network again. Do you have some ideas?
