### ISSUE TITLE
Allow Setting Storage Method when adding files

### ISSUE THREAD

**Issue by teliov** [maennchen/ZipStream-PHP#54]
When adding files to the zip stream, the user should be able to specify the compression method (0 for NOCOMPRESS or 8 for DEFLATE)

Currently it defaults to DEFLATE but in the internal methods used in the ```addFile```, method there is an option to set the compression method.

I ran into a case where it was necessary to store some small files in an uncompressed state.

Would be happy to send in a pull request

**Comment by maennchen** [comment]
Hi @teliov 

That sound like a good idea. I'd be happy to accept a PR for that.

**Comment by teliov** [comment]
Just sent in one at #57 . Let me know if this works
