### ISSUE TITLE
help me,sir

### ISSUE THREAD

**Issue by kjin9174** [maennchen/ZipStream-PHP#63]
I am facing memory-limit error in wp plugin code.
My code is below
        function zipData($source, $destination) {
            if (extension_loaded('zip')) {
                if (file_exists($source)) {
                    $zip = new ZipArchive();
                    if ($zip -> open($destination, ZipArchive::CREATE) === TRUE) {
                        $source = realpath($source);
                        if (is_dir($source)) {
                            $iterator = new RecursiveDirectoryIterator($source);

                            $iterator->setFlags(RecursiveDirectoryIterator::SKIP_DOTS);
                            $files = new RecursiveIteratorIterator($iterator, RecursiveIteratorIterator::SELF_FIRST);
                            foreach ($files as $file) {
                                $file = realpath($file);
                                if (is_dir($file)) {
                                    $zip->addEmptyDir(str_replace($source . '/', '', $file . '/'));
                                } else if (is_file($file)) {
                                    $zip->addFromString(str_replace($source . '/', '', $file), file_get_contents($file));
                                }
                            }
                        } else if (is_file($source)) {
                            $zip->addFromString(basename($source), file_get_contents($source));
                        }
                    }
                    return $zip->close();
                }
            }
            return false;
        }

        ini_set('max_execution_time', 600);
        ini_set('memory_limit','1024M');
        ini_set('upload_max_filesize','5000M');
        zipData($upload_dir['basedir'], $upload_dir['basedir'].'/Jincowboy/JinBackupMedia'. time() .'.zip');
but i am facing memory limit. so i checked google. i saw stream zipfile generation is needed for avoding memory limit.
But i couldn't confirm about this.
I want my code allow memory limit and creation zip file of big file directory with big files

**Comment by maennchen** [comment]
@kjin9174 If you have specific questions about one of the ZipStream API's, I'm happy to help. But I wont write the code for you.
