### ISSUE TITLE
compression option support

### ISSUE THREAD

**Issue by OliverLeitner** [maennchen/ZipStream-PHP#64]
hi everyone,

maybe im blind (yes, thats a possibility...)

are the compression options, that usually come with zip, available with zipstream-php?

i.e. zip -r **-9** somefile.zip somefile.sql

**Comment by maennchen** [comment]
Hi @OliverLeitner 

The library does not have that option. You could however make a PR for that.

On those lines we provide `6` as the compression level:
* https://github.com/maennchen/ZipStream-PHP/blob/master/src/ZipStream.php#L323
* https://github.com/maennchen/ZipStream-PHP/blob/master/src/ZipStream.php#L350

Here we leave it with the default values:
* https://github.com/maennchen/ZipStream-PHP/blob/master/src/ZipStream.php#L646
* https://github.com/maennchen/ZipStream-PHP/blob/master/src/ZipStream.php#L716

You could make a PR that sets a global compression level option and use it in those places.

**Comment by OliverLeitner** [comment]
thank you for the reply...

a little update... i had to remove the dependency on this library from my project, since the resulting zip couldnt pass the upload to the portal i am creating it for. (shows error in zip file...)

works fine with gnu zip and microsoft's windows explorer implementation of zip. and i was on a clock with that project. i couldnt afford the time that the format debugging wouldve taken, so i went with escapeshellcmd.

**Comment by maennchen** [comment]
@OliverLeitner There are many ZIP clients that can not handle the full specification unfortunately. We can't comply with many clients because of that.

I'm going to leave this issue open. Maybe someone else needs this possibility and can send a PR.
