### ISSUE TITLE
Release announcement URL could be wrong

### ISSUE THREAD

**Issue by freekmurze** [maennchen/ZipStream-PHP#66]
The readme mentions a release announcement at the url: http://pablotron.org/?cid=1535

The page now displays "I'm in the process of migrating to a new server."

Maybe I'm just unlucky and visiting the page at the wrong time. But if already completed the migration process, it's probably best to update the url in the readme.

Thanks!

**Comment by donatj** [comment]
It's probably just broken. It's a link to the original no longer maintained library this was forked from site.

**Comment by maennchen** [comment]
@freekmurze Let's wait and see if it comes back. Otherwise we can remove it from the `README`.

**Comment by maennchen** [comment]
Doesn't seem to come back. I commented out the reference to the page for now: 74818d4

**Comment by donatj** [comment]
@maennchen He's got a note on the root "I'm in the process of migrating to a new server." - so my guess is it'll be back

**Comment by maennchen** [comment]
@donatj I decided to comment it out since it‘s like this for nearly 2 weeks. I‘ll add it back as soon as it‘s live again.
