### ISSUE TITLE
how to know when the file has finished downloading ?

### ISSUE THREAD

**Issue by ctf0** [maennchen/ZipStream-PHP#68]
i thought i have to call `$zip->finish()` to download the file and close the stream, but apparently its not needed and the package will stream as you add the files to `$zip->addFileFromStream()`

i tried something like
```php
$done = $zip->finish();
if ($done) {
    // do something
}
```

but the `do something` part never fires.

so what exactly `$zip->finish()` does & how do i know when the stream has finished and file has downloaded ?

**Comment by maennchen** [comment]
Hi @ctf0 
As the name if the lirary implies, the zip is streamed. If we would wait until finish we would need to have the whole zip contents in memory which would defy the purpose.

The headers are sent when you add any file the first time. The code is synchronous. The finish method sends some data to finish the zip.

You do not need to check for anything after the finish. You will be done at that point.

Note that you can‘t really do much after the finish. The HTTP response is sent and you can not render any html for example. Also make sure there are no errors / warnings as they will also be downloaded into the zip and will corrupt it.

**Comment by ctf0** [comment]
oh okay, thanks for the clarification.

i was using it so i can notify the user and do some ops on the client side.

last question, in the [Symfony example](https://github.com/maennchen/ZipStream-PHP/blob/master/doc/Symfony.md) it says we need to use `StreamedResponse` , but its seems its not really needed as the attached headers the package add already take care of that part, or am i missing something ?

**Comment by maennchen** [comment]
@ctf0 I would recommend doing it with the StreamedResponse, since this is the intended way for Symfony. It‘ll work without though too.

**Comment by ctf0** [comment]
thanx again.

> a note about `fopen()`

atm if you received an error like `403 forbidden`, the streaming wont die but instead will continue and will give a corrupted file, so a solution would be using `@fopen()` and now you will be able to catch the error inside the else as expected.
