### ISSUE TITLE
Update version string

### ISSUE THREAD

**Issue by akamustang** [maennchen/ZipStream-PHP#69]
In `ZipStream.php` the `VERSION` is still set at `0.3.0` even though the latest release is `0.5.1`.

**Comment by maennchen** [comment]
Good catch, I marked it as deprecated and released version `v0.5.2`. The version can be obtained (and guaranteed to be correct) using composer.

**Comment by akamustang** [comment]
Hmm okay, and which file is the composer version in, I grepped the codebase and found no mention of `0.5.2`.

**Comment by maennchen** [comment]
@akamustang 

There's a few ways to do it by hand:
* You can find it in the `vendor/composer/installed` file.
* You can find it in the `composer.lock`file.
* With the command line you can use `composer show maennchen/zipstream-php`.

As an alternative this should work: https://packagist.org/packages/ocramius/package-versions

**Comment by akamustang** [comment]
Sadly these locations don't exist unless you are using composer, which clearly I'm not. I guess I'll just have to manually update the version string. Thanks for replying.

**Comment by maennchen** [comment]
@akamustang This library is targeted for composer. The `VERSION` const is an artifact from the original project which was distributed using a zip file.

If I find some time in the future, I'm going to refactor the library in the future which will require installing dependencies (of ZipStream) using composer.
