### ISSUE TITLE
Corrupt Archive with Images

### ISSUE THREAD

**Issue by paciliojoe** [maennchen/ZipStream-PHP#73]
I am able to successfully create, stream, and open a zip containing text files, however, the moment I add a non-text file, I'm no longer able to open the zip.  I get the following error from Windows:
```
Windows cannot open the folder.
The Compressed (zipped) Folder 'path\to\archive.zip' is invalid.
```

I was able to get everything to be successful with a tiny image (8kb), but the error continued to occur for a slightly larger file (27kb) and all other files I've tried.  I'm not sure if this is a file size issue, a local setting issue, or something else, but I have run into the same issues with v0.5.2, 0.5.0, and 0.4.1.  Below is my code with v0.5.2, the last version I tested.
```
$zip = new ZipStream('files.zip');
$zip->addFile('test-file2.jpg', file_get_contents('files/test2.jpg'));
$zip->finish();
```
I have tried to use addFile and addFileFromPath - both with the same result.  The above code works if I use 'files/test.txt' instead of the jpg.

**Comment by yanchoo** [comment]
Try 
```
ob_end_clean();
$zip = new ZipStream('files.zip');
```

**Comment by NicolasCARPi** [comment]
@paciliojoe did you try what @yanchoo is suggesting?

You might also want to try the latest version from master (replace the version in composer.json with "dev-master").

**Comment by NicolasCARPi** [comment]
ping @paciliojoe

**Comment by paciliojoe** [comment]
Sorry everyone.  I had moved on to a different solution, so I hadn't been checking back in on this thread.  I will work on getting it set back up and give it a try with @yanchoo's suggestion.

**Comment by paciliojoe** [comment]
The latest version does appear to be working for me now with @yanchoo's suggestion.  Thanks!
