### ISSUE TITLE
Is it possible to create archive within an archive?

### ISSUE THREAD

**Issue by davor-humanity** [maennchen/ZipStream-PHP#75]
Hi @maennchen, I was wondering if it's possible to nest archives using your library. Everything is working great for me when streaming just one big archive, but I have a requirement of exporting data for multiple entries that need to be individually zipped in their own archives. I can easily create folders, but ideally a structure would be something like this:

```
MainArchive.zip
 |--SubArchive1.zip
   |--Text1.txt
   |--Image1.jpg
 |--SubArchive2.zip
   |--Text2.txt
   |--Image2.jpg
 |--SubArchive3.zip
   |--Text3.txt
   |--Image3.jpg
```

**Comment by NicolasCARPi** [comment]
Hello,

The small zips cannot be written to disk? You  have to stream the whole thing?

**Comment by maennchen** [comment]
In theory you can write the smaller zip files into its own stream and then add the stream to the outer zip. Have a look at `setOutputStream` https://github.com/maennchen/ZipStream-PHP/blob/master/src/Option/Archive.php#L224

**Comment by maennchen** [comment]
Closed because of inactivity.
