### ISSUE TITLE
The Native OSX-Unzipper can not handle the Archives.

### ISSUE THREAD

**Issue by superjunky** [maennchen/ZipStream-PHP#76]
I'm struggling to get correct archives that can be unzipped by the native OSX-Unzipper.

I'm reading and testing for some time now, but now I'm wondering if it is even possible for version >1. (I read several of these type of issues.)

- Can you confirm `->addFileFromStream()` does not work for the OSX-Unzipper?
- If so, would it be wise to use version 0.5?

For a clear reference I'll post the code that I used, and a test.zip file.

[test.zip](https://github.com/maennchen/ZipStream-PHP/files/2084809/test.zip)

```
$options = new ZipStream\Option\Archive();
$options->setZeroHeader(true); 
$options->setContentType( 'application/octet-stream' ); 
$options->setSendHttpHeaders(true);
$options->setHttpHeaderCallback('header');

$zip = new ZipStream\ZipStream( $filename . '.zip', $options );

foreach ( $files as $file ) {

	if ( ! file_exists( $file ) ) {
		continue;
	}

	if ( ! $stream = fopen( $file, 'r' ) ) {
		$zip->addFileFromStream( basename( $file ), $stream );        
	} else {
		die( __( 'Could not open stream for reading', 'photosessions' ) );
	}

}

$zip->finish();
```

**Comment by kolesar-andras** [comment]
OSX-Unzipper may not support zero header. Delete the following line:

```php
$options->setZeroHeader(true);
```

It's a shame that archive utilities do not support old and widely used options.

**Comment by superjunky** [comment]
Unfortunately that gives the same error for OSX-Unzipper.

**Comment by newPOPE** [comment]
I trying this with custom output stream and on OSX works fine (but I run it in Docker(debian)).

**Comment by NicolasCARPi** [comment]
@superjunky why do you `setContentType( 'application/octet-stream' ); `, you know it's a zip so you can use 'application/zip' ;)

Also please provide the version you are using of Mac OS X and OSXUnzipper utility.

**Comment by superjunky** [comment]
@NicolasCARPi thanks for the pointer. What actual difference will it make to change the content_type?

The version of 'unzip' is 6.0

**Comment by NicolasCARPi** [comment]
> What actual difference will it make to change the content_type?

It's to tell the browser what to expect. Some users for instance will download zip immediatly, others will have a dialog to select the action (save or extract directly). It doesn't change anything to the file itself afaik.

> I reverted back to ZipStream version 0.3.0. This solved my issues.

Well that's interesting, it means a regression was introduced. Now let's go `git bisect` some commits…

**Comment by superjunky** [comment]
> Well that's interesting, it means a regression was introduced. Now let's go git bisect some commits…

Wait, hold on. I got the ZS version by checking ZipStream.php, but now I'm looking at the versions here at github, it appears to be 0.5.2

**Comment by NicolasCARPi** [comment]
Ok. I'm trying to reproduce the issue here and in the code you provided, shouldn't the line `if ( ! $stream = fopen( $file, 'r' ) ) {` be without the `!`?

**Comment by superjunky** [comment]
Yes, `!` should not be there. It must have been a temp typo. I know for certain this was not the cause of the problem at the time, due to the fact I produced working zip's if unpacking with archive-apps other than the OSX unzip.

If not mistaken, by reading other Issues, I remember more reports about trouble with the Alpha version and OSX unzip. In the end I assumed, for it being an Alpha, it was not yet expected to work 100% anyway.

But by reading your reply, there should be no issue at all?
Though I'm willing, it's hard to assist at the moment. I took the code live, and cleaned all my debugging.

**Comment by NicolasCARPi** [comment]
No I'm not implying that there is no issue. I produced the zip file, now I'm waiting for my girl to come back home with her macbook so I can try it =)

**Comment by superjunky** [comment]
You're telling me you don't have a pile of mac's lying around? ;p

**Comment by NicolasCARPi** [comment]
Ok so the bug is reproducible. With a bit of chance, fixing issue #84 will also fix this problem!

**Comment by cleggypdc** [comment]
Hey I'm also experiencing this problem using the latest dev-master **and** with the change made in https://github.com/maennchen/ZipStream-PHP/pull/90 - here's the code I'm using which works with windows native unzip:

    $response = new StreamedResponse(function() use($suggestedFilename, $fileList)
    {
            // Define suitable options for ZipStream Archive.
            $opt = new \ZipStream\Option\Archive();
            $opt ->setZeroHeader(true); 
            $opt ->setContentType( 'application/octet-stream' ); 
            $opt ->setSendHttpHeaders(true);
            $opt ->setHttpHeaderCallback('header');

            ob_end_clean();
            $zip = new ZipStream("{$suggestedFilename}.zip", $opt);

            foreach ($fileList as $fileInfo) {
                if ($streamRead = fopen($fileInfo['fileSystemPath'], 'r')) {
                    $zip->addFileFromStream($fileInfo['zipPath'], $streamRead);
                } else {
                    // todo something here in Application logger
                }
            }

            $zip->finish();
        }, 200, [
            'X-Accel-Buffering' => 'no',
        ]);`

**Comment by NicolasCARPi** [comment]
@cleggypdc What is the output of `unzip -Zv archive.zip`?

Is the setZeroHeader option necessary?

**Comment by cleggypdc** [comment]
@NicolasCARPi looks like the setZeroHeader wasn't neccessary, thanks!
