### ISSUE TITLE
How alive is this library?

### ISSUE THREAD

**Issue by NicolasCARPi** [maennchen/ZipStream-PHP#79]
Hello,

I want to include your library for downloading zip files in my project ([elabftw](https://github.com/elabftw/elabftw/)).

I tried the latest stable version. It works. Tried the alpha1 version, it works too. But the alpha has been released in april and we are in august now.

I also see that you do not have that much time to dedicate to this project (see [comment](https://github.com/maennchen/ZipStream-PHP/issues/65#issuecomment-350266317)).

My questions are: is this project actively maintained? Will you release a stable version 1.0 soon?

Anyway, thanks for this great library, it helps me a lot for tackling timeout issues I have when generating big zip files :)

Cheers,
~Nico

**Comment by maennchen** [comment]
@NicolasCARPi There are still some issues with the alpha version. I do not have the time to fix them. I do not expect a stable release soon if there's not any other person willing to contribute.

If there are some people willing to participate, I'll be around for code reviews, merging PR's etc. but I can't do it alone.

**Comment by NicolasCARPi** [comment]
Ok I see. What issues do you think are blocking? #67 ? Last comment seems to indicate it should not happen anymore in php 7.1.

I'm willing to spend some time helping you to get to 1.0. The code is well formatted and annotated, so if you point me to some reproducible issues I will have a look and hopefully solve the issue. :)

~Nico

**Comment by maennchen** [comment]
Actually I thought that #65 was blocking it. But as you pointed out, that might no longer be the case. I did also not get other bad feedback and therefore we could nearly merge it.

The only thing missing then would be about documentation. (Mostly ZeroHeader and #74)

**Comment by maennchen** [comment]
Thanks by the way for looking at the issues. I appreciate that.

**Comment by NicolasCARPi** [comment]
Closing this as the lib IS alive ;)

The objective now is to release a proper 1.0.0 version before I get to release the new stable version of my app.
