### ISSUE TITLE
Separating documentation from code

### ISSUE THREAD

**Issue by NicolasCARPi** [maennchen/ZipStream-PHP#81]
Hello,

IMHO the `doc` directory should be removed and its content should be added to the wiki. It's much better to separate documentation from the project.

Basic usage should still be in the README.

**Comment by maennchen** [comment]
@NicolasCARPi I'm going to add you as a contributor so you have access to the wiki. Please do not merge PR's without a code review though.

**Comment by NicolasCARPi** [comment]
Ok thanks :)
