### ISSUE TITLE
Compressed files have no permissions set

### ISSUE THREAD

**Issue by NicolasCARPi** [maennchen/ZipStream-PHP#84]
# Description of the problem

When compressing files (using addFileFromPath()) with ZipStream-PHP, the files inside the zip archive will lose all UNIX permissions. And after unzipping, directories work fine but files have no permissions set:

Output of `unzip -Zv archive.zip` with ZipStream:
Unix file attributes (000000 octal):            ?---------

Output of `unzip -Zv archive.zip` with ZipArchive from PHP:
Unix file attributes (100666 octal):            -rw-rw-rw-

After unziping, the files have no permissions set:
ls -l:
---------- 1 user wheel     799 Aug  1 12:37  file1.txt

There is no mention of permission in the source code of ZipStream and I'm not sure how one could go about adding this in the library. @maennchen any idea?

Workaround is of course to chmod the files after unzipping, but that is not a conceivable solution for normal users.

# Example code

~~~bash
mkdir permbug
cd permbug
composer require maennchen/zipstream-php dev-master
echo "file1 content" > file1.txt
~~~

Content of index.php:

~~~php
<?php

require_once 'vendor/autoload.php';

use ZipStream\ZipStream;
use ZipStream\Option\Archive as ArchiveOption;

$zipPath = 'file.zip';

$opt = new ArchiveOption();
$opt->setContentDisposition = 'attachment';
$opt->setContentType = 'application/x-zip';
$opt->setSendHttpHeaders(true);
$opt->setHttpHeaderCallback('header');
$zip = new ZipStream($zipPath, $opt);
$zip->addFileFromPath('zippedfile', 'file1.txt');
$zip->finish();
~~~

~~~bash
php -S locahost:7000
# from another shell
curl http://localhost:7000 -o file.zip
unzip -Zv file.zip|grep octal
~~~

It will show ?-------- instead of correct permissions.

# Informations

* ZipStream-PHP version: 1.0.0-alpha
* PHP version: 7.1.17

edit: adding file.zip

[file.zip](https://github.com/maennchen/ZipStream-PHP/files/2249314/file.zip)

**Comment by newPOPE** [comment]
Is there any solution for this?

**Comment by maennchen** [comment]
To implement this feature, you‘ll have to look into the zip standards and find out how the permissions are stored. I suppose this information is somewhere in the file header.

**Comment by newPOPE** [comment]
Nice, do you have some good link for ZIP standards I can look into. Found some on google but just check.

**Comment by maennchen** [comment]
I can't really point you to any good resources there. Especially since I believe that the permissions are stored in the extra fields of the local file header and this one is not specified in the main zip specification.

**Comment by maennchen** [comment]
https://stackoverflow.com/a/13633772

**Comment by maennchen** [comment]
https://unix.stackexchange.com/questions/14705/the-zip-formats-external-file-attribute

**Comment by maennchen** [comment]
The External FIle Attributes are set here: https://github.com/maennchen/ZipStream-PHP/blob/master/src/File.php#L457

Together with the table from stackexchange you should able able to put it together.

I would recommend the following things:

* Add a Permissions Parameter (optional) to `addFile`, `addFileFromPath`, `addFileFromStream`, `addFileFromPsr7Stream`
* Default the parameters to null and don't set any flags if it is null
* Default the parameter of `addFileFromPath` to the files current permissions
* Take the permissions as an octal number like for example http://php.net/manual/en/function.chmod.php

That this works good, we're also going to need a `addDirectory` method that does the same and sets the `S_IFDIR` flag.

To make this clean I would propose that we make directory handling more explicit before releasing the next major version. Files can only be added if the target directory in the zip was already created using `addDirectory`.

**Comment by newPOPE** [comment]
Thanks, I will check it because for us is showstopper. Can you describe me a little what is number 32 for external attributes?

**Comment by maennchen** [comment]
@newPOPE Sure,

`32` is `0100000` in binary.

According to the Stackexchange link, this means `S_IFREG` => Marks the file as a regular file.

**Comment by maennchen** [comment]
@newPOPE 

The field is generally 4 bytes long (4 * 8 bits),

This would mean it would look like `10000000 00000000 00000000 00000000` empty in binary.

This would mean it would look like `000000 00000` empty in binary.

I believe that only the later half (16 bits) is actually used.

`32` in octal would be `100000` in octal and according to the list be the option `S_IFREG`. That means that the file is a regular file and not a socket / directory, symbolic link etc.

Let me make an example: You have a regular file which should be readable and writable by the owner:

```
Names:  S_IFREG           | S_IRUSR           | S_IWUSR           = Result
Octal:  100000            | 000400            | 000200            = 100600
Binary: 10000000 00000000 | 00000001 00000000 | 00000000 10000000 = 10000001 10000000

```

**Comment by maennchen** [comment]
Example in PHP:

```php
const S_IFREG = 0100000;
// same but in binary:
// const S_IFREG = 0b1000000000000000;
// same but in dec:
// const S_IFREG = 32;

const S_IRUSR = 0000400;
const S_IWUSR = 0000200;

$resultingBits = S_IFREG | S_IRUSR | S_IWUSR;
```

See http://php.net/manual/de/language.operators.bitwise.php

**Comment by maennchen** [comment]
I'm sorry, I'm making a mess. `32` dec is not `100000` octal. It should be `0000040` in octal and that also doesn't make sense.

**Comment by maennchen** [comment]
You'll have to try around a little to find out the details. I would focus on those resources:

* https://www.forensicswiki.org/wiki/ZIP
* https://unix.stackexchange.com/questions/14705/the-zip-formats-external-file-attribute
* https://packages.debian.org/source/stable/unzip (Source Code of Unzip might also be helpful)

**Comment by newPOPE** [comment]
Thought will be easy :D. I am on it.

**Comment by maennchen** [comment]
Haha, it's always down the rabbit hole with the zip specification (or lack thereof).

**Comment by newPOPE** [comment]
After some research and tests (comparing hex, binary values :D) got it, maybe.

Looks like that lib has bad pack format param on line which you mentioned should be `N` for setting the correct bytes and when the value is `46721` on OSX (forklift, 7z) permissions are good.

**Comment by newPOPE** [comment]
@NicolasCARPi you are welcome. I cannot find out how this https://unix.stackexchange.com/questions/14705/the-zip-formats-external-file-attribute handle it. Because I trying combinations but nothing worked as expected.

**Comment by newPOPE** [comment]
@maennchen I would like to prepare a PR with all what you mentioned but I must find out how the permissions worked :D.

**Comment by diaryevil** [comment]
I try to use function stat() to get the mode of file, and it works on my machine :-)

this function returns an array and key 'mode' contains  the value we need
for example, mode of file1 is 100644
`-rw-r--r--  1 root root  59 Jul  8 02:11 file1`
Array returnd by function stat() contains
 `["mode"]=>int(33188)`
33188 is demical and equip to 100644 in octal, this value is easy to get

After that, 33188 looks like `10000001` `10100100` in binary, 2 bytes long
But External FIle Attributes is 4 bytes long, how to set 33188 in 4 bytes?
Well, in my codes
`$cdrec .= pack('V', $mode);            // external file attributes - 'archive' bit set`
What I put in $mode is `10000001` `10100100` `00000000` `00000000` -- `81ed` `0000`(the result of hexdump , it may be different in Big-Endian and Little-Endian), added `<< 16`

Otherwise, my code's version is in Feb 2018. in this version I found the field `version made by` in `central directory structure` was `0000`. During my test, it may cause error when unzip set the mode of file, I set it to `0317`(Unix) and possible error disappear. Now this field isn't set to `0000` any longer, but i would like to mention it for any potential bug

At last, this is my first experience on github, I hope I can help it.
I viewed the source code of zip and unzip, but just tested a few times. it works on my machine, and may be some errors I haven't found out.

**Comment by NicolasCARPi** [comment]
@diaryevil Thanks for investigating this bug. Would it be possible for you to try and make a pull request? We'll then test and assess your code before a eventual merge.

**Comment by shouze** [comment]
@diaryevil @NicolasCARPi any update about the fix? We're willing to help as we would be very pleased to use this lib.

**Comment by shouze** [comment]
I've tried to make a diff between release 0.3.0 wich was said to work as discussed in https://github.com/maennchen/ZipStream-PHP/issues/76#issuecomment-409254974
So here's a maybe something that it would be cool to discuss?
```php
<?php
// From release 0.3 that seems to work 
// as discussed here: https://github.com/maennchen/ZipStream-PHP/issues/76#issuecomment-409254974
// https://github.com/maennchen/ZipStream-PHP/blob/6ef77339a768f5066310a1c908cd50cf6a5b05d7/src/ZipStream.php
$fields = [ // (from V,F of APPNOTE.TXT)
    ['V' => 0x02014b50],                     // 1.  Central file header signature
    ['v' => (6 << 8) + 3],                   // 2.  Version made by
    ['v' => (6 << 8) + 3],                   // 3.  Version needed to Extract
    ['v' => 0x00],                           // 4.  General purpose bit flags - data descriptor flag set
    ['v' => $meth],                          // 5.  Compression method
    ['v' => $dts],                           // 6.  Timestamp (DOS Format)
    ['V' => $crc],                           // 7.  CRC32 of data (0 -> moved to data descriptor footer)
    ['V' => $zlen],                          // 8.  Length of compressed data (forced to 0xFFFFFFFF for zero header)
    ['V' => $len],                           // 9.  Length of original data (forced to 0xFFFFFFFF for zero header)
    ['v' => strlen($name)],                  // 10. Length of filename
    ['v' => 0],                              // 11. Extra data (see above)
    ['v' => strlen($comment)],               // 12. File comment length
    ['v' => 0],                              // 13. Disk number start
    ['v' => 0],                              // 14. Internal file attributes
    ['V' => 32],                             // 15. External file attributes
    ['V' => $ofs],                           // 16. Relative offset of local header
];		
// pack fields, then append name and comment
$ret = $this->packFields($fields) . $name . $comment;


// To release 1.0.0 that is broken on macOS
const FILE_HEADER_SIGNATURE = 0x04034b50;
$fields = [
    ['V', ZipStream::FILE_HEADER_SIGNATURE],  // 1.  Central file header signature
                                              // 2.  Version made by: is it now included into ZipStream::FILE_HEADER_SIGNATURE?
    ['v', $this->version->getValue()],        // 3.  Version needed to Extract
    ['v', $this->bits],                       // 4.  General purpose bit flags - data descriptor flag set
    ['v', $this->method->getValue()],         // 5.  Compression method
    ['V', $time],                             // 6.  Timestamp (DOS Format)
    ['V', $this->crc],                        // 7.  CRC32 of data (0 -> moved to data descriptor footer)
    ['V', $this->zlen->getLowFF($force)],     // 8.  Length of compressed data (forced to 0xFFFFFFFF for zero header)
    ['V', $this->len->getLowFF($force)],      // 9.  Length of original data (forced to 0xFFFFFFFF for zero header)
    ['v', $nameLength],                       // 10. Length of filename
    ['v', strlen($footer)],                   // 11. Extra data (see above)
                                              // 12. File comment length
                                              // 13. Disk number start
                                              // 14. Internal file attributes
                                              // 15. External file attributes
                                              // 16. Relative offset of local header
];
// pack fields and calculate "total" length
$header = ZipStream::packFields($fields);
```

**Comment by shouze** [comment]
BTW packField method has also evolved between release 0.3.0 & 1.0.0/master from that one:
```php
function packFields($fields) {
    list($fmt, $args) = array(
        '',
        array()
    );
    
    // populate format string and argument list
    foreach ($fields as $field) {
        $fmt .= $field[0];
        $args[] = $field[1];
    }
    
    // prepend format string to argument list
    array_unshift($args, $fmt);
    
    // build output string from header and compressed data
    return call_user_func_array('pack', $args);
}
```

To that one:
```php
function packFields(array $fields): string
{
    $fmt = '';
    $args = [];
    // populate format string and argument list
    foreach ($fields as [$format, $value]) {
        if ($format === 'P') {
            $fmt .= 'VV';
            if ($value instanceof Bigint) {
                $args[] = $value->getLow32();
                $args[] = $value->getHigh32();
            } else {
                $args[] = $value;
                $args[] = 0;
            }
        } else {
            if ($value instanceof Bigint) {
                $value = $value->getLow32();
            }
            $fmt .= $format;
            $args[] = $value;
        }
    }
    // prepend format string to argument list
    array_unshift($args, $fmt);
    // build output string from header and compressed data
    return pack(...$args);
}
```

**Comment by shouze** [comment]
@NicolasCARPi I've made some tests... and.. guess what... when I restore `ZipStream::ZIP_VERSION_MADE_BY` value to the one of pre-1.0.0 releases (`(6 << 8) + 3` instead of `0x031E`): it fixes permission issue on `macOS` / `Mac OSX` platforms so... fixes #76.

@brokencube you are [the author](https://github.com/maennchen/ZipStream-PHP/commit/22789a04b0fa3391ff4bc34ac2b2222fa56423f2#diff-3b3e03a6fce80d7f70706fab060b492aR23) apparently, is it OK to revert this value?
@kolesar-andras & @maennchen you've also participated when it was changed in https://github.com/maennchen/ZipStream-PHP/commit/22789a04b0fa3391ff4bc34ac2b2222fa56423f2, any input on your side about that?

Anyway, I've made a PR https://github.com/maennchen/ZipStream-PHP/pull/90 to fix that if you're ok to revert to original value.

**Comment by brokencube** [comment]
I'm guessing the large file + psr 7 functionality was based on the ZipStream64 fork I made (https://github.com/brokencube/ZipStream64)  - I seem to have a commit where I changes the version back to older value to get Mac support working properly (https://github.com/brokencube/ZipStream64/commit/09fa19e3acfbb9534bcc7958c697a044361522ae) Hope that helps - been a couple of years since I did anything with it!

**Comment by brokencube** [comment]
I'm happy my code seems to have been of some use and merged back into it's source, though I'm a little sad my name appears to have been stripped from the contribution in the cleanup :/ Oh well.

**Comment by newPOPE** [comment]
Hello, I wanted to fix this issue as I mentioned here https://github.com/maennchen/ZipStream-PHP/issues/84#issuecomment-415992511 but in meanwhile I realized that permissions in archive are for nothing. As a user: when I get a zip file and can extract it but permissions are not good I just set it to correct and go forward. So from my point of view is fileperms in archive totally unusable.

**Comment by newPOPE** [comment]
Hello, I wanted fix this issue with support file permissions as mentioned here https://github.com/maennchen/ZipStream-PHP/issues/84#issuecomment-415708651. But after some time using this commit https://github.com/newPOPE/ZipStream-PHP/commit/98da980f2380ff146f4f3ecfdcb7fabce395d66c I just realized that file permission in archive are totally unusable. As I end user of archive I just download archive, extract it (with or without password). If everything is okay files are extracted correctly (correct content) but I cannot read it so fix the permissions and I am done. So my from my point of view I have zip but cannot read files in it?. It doesn't make sense.

**Comment by NicolasCARPi** [comment]
@newPOPE Did you try with this (simple) change: https://github.com/maennchen/ZipStream-PHP/pull/90/files ?

**Comment by newPOPE** [comment]
@NicolasCARPi not for now. I will try it. Do you just need a confirmation of working? Or anything else?.

**Comment by NicolasCARPi** [comment]
Well, the more users can confirm it fixes the issue, the better :)

**Comment by brokencube** [comment]
> @brokencube Sorry about that, I wasn't aware of this. Would you want to be mentioned in the authors section of the README?

Oops, that comment of mine was a little more passive aggressive than I meant to be! Sorry. It would be nice to be in the Readme, but I acknowledge that my additions were fairly small - my own codebase's Readme admits that the work was 90% yours anyway!

**Comment by maennchen** [comment]
@brokencube I was not aware that you made any contributions since the PR was not posted by you. I'm very for that anyways. I think that this is important. Please make a little PR with the README change and I'll gladly merge that.
