### ISSUE TITLE
getCrc32() must be of the type integer, float returned

### ISSUE THREAD

**Issue by millsoft** [maennchen/ZipStream-PHP#88]
# Description of the problem

I get the following TypeError in the getCrc32 method.
Return value of JDWil\ZipStream\Stream\WriteStream::getCrc32() must be of the type integer, float returned

# Example code
```
$zipStream = \JDWil\ZipStream\ZipStream::forFile('php://output');
$zipStream->addFileFromDisk($saveAs, $file);
$zipStream->close();
```

`$saveAs` is just a string with the file name for the zip file (eg. `file.pdf`) and `$file` is the absolute path to the file. The PDF file is about 100 kb in size.
# Informations

* ZipStream-PHP version: composer.json says ^0.1.2
* PHP version: tried with 7.0, 7.1, 7.2

Please include any supplemental information you deem relevant to this issue.

I tested it first with windows (xampp) I thought it was a windows issue, then I moved the code to production (Linux), same error.

I fixed the problem for myself by editing `WriteStream.php` and removed the `:int` part in line 126. So it looks now like this:

```
    public function getCrc32()
    {
        return $this->crc32Params->crc32;
    }
```

Can you please fix it or tell it what I can / should do?

**Comment by NicolasCARPi** [comment]
Hello,

It seems you are using jdwil/zipstream, a different package from the one associated with this repository.

**Comment by millsoft** [comment]
OMG, you are right -.- sorry, I had multiple tabs open. You can remove this.
