### ISSUE TITLE
File size unknown when downloading.

### ISSUE THREAD

**Issue by ersan** [maennchen/ZipStream-PHP#89]
# Description of the problem

I was under the impression that when you set SendHttpHeaders and StatFiles to true that the headers would report the content length to the browser so it knows how large the file it is downloading is.  Is this the case?

When the browser downloads the created ZIP it doesn't show the size of the file it's downloading.  Now that I think about it I suppose that can't be known ahead of time since it is compressing on the fly, but for my use I'm just using STORE instead of deflate so I should be able to send that information myself?  Any idea how I might go about doing that?  If this is determined by the content-length header is there any overhead that comes from making the ZIP that I could calculate beforehand?

EDIT: I see now that if I add up the size of all the files beforehand I can send a content-length header and it is reflected in the browser.  Is there any way to reliably determine how much overhead will be created by the ZIP wrapper beforehand to get an accurate file size?  Or even an estimate?  As long as it's slightly longer than the actual size it seems to work fine.

# Informations

* ZipStream-PHP version: 1.0.0-alpha.1
* PHP version: 7.2.8

Please include any supplemental information you deem relevant to this issue.

**Comment by lksnmnn** [comment]
Overestimating is not good if you want a broad browser support (i.e., mobile).

What I am currently trying to archive is to provide ZIP stream download with a `content-length` header so the user knows how long the download will take, as the browser estimates it.

For this I summed up all file sizes prior to streaming them with ZipStream. This works perfectly on most browsers I tested, but fails miserably in iOS (Safari, iOS 12). It seems the browser can't handle my 'overestimation' since the resulting file was indeed smaller then my provided length. A quick  curl confirmed this (`curl: (18) transfer closed with 464151 bytes remaining to read`).

We mostly provide PDFs, JPGs and mp4s, so the compression is not doing all that much and I will try to disable it in favour of having a `content-length` header.

Btw. having a smaller `content-length` seems to be working, so a hacky solution would be to guesstimate the compression gains and subtract them from your calculated size. But I'll try to disable compression completely.

**Comment by NicolasCARPi** [comment]
@lksnmnn could you try on iOS to download a .zip from a github repository? Because github doesn't send any content-length header.

**Comment by lksnmnn** [comment]
Yeah. It works without content-length header, but I'd like to provide users with a progress since some ZIP files can be several GB large.

**Comment by lksnmnn** [comment]
I could check the user agent ;)

**Comment by lksnmnn** [comment]
So... using `ZipStream::METHOD_STORE` within `addFileFromStream()` pushed me in the other direction. Now I am getting corrupted files, since the archive is about 30kb larger then my content-length header.

I will opt for leaving it out for now. -.-

**Comment by maennchen** [comment]
This is not possible by design. If this was possible, then the zip headers also wouldn't need the streamed flag.

The file either has to be created on disk and then downloaded (Content-Length known) or it can be streamed (Content-Length not known).

**Comment by ersan** [comment]
Sorry for reopening this so late, but I'm finally working on my project that uses this.

Turns out there is a way to calculate the overhead, after reading [this post](https://stackoverflow.com/questions/22346487/how-can-we-estimate-overhead-of-a-compressed-file) (which appears to be wrong in this case) and some trial and error it appears to be:
22 bytes
+ 76 bytes per file
+ 2x the length of the path/filename of each file

Adding that to the actual size of the files in the archive, I've been able to use this on roughly 40 different ZIPs of widely varying sizes without issue, and multiple browsers are able to download the file with progress bars, as well as extract without issue.

Whether you want to implement this in ZipStream or not I don't know, but just thought I'd let anyone else that came across this know that it is possible.

**Comment by ersan** [comment]
Sorry for replying to this so late, but I'm finally working on my project that uses this.

Turns out there is a way to calculate the overhead, after reading [this post](https://stackoverflow.com/questions/22346487/how-can-we-estimate-overhead-of-a-compressed-file) (which appears to be wrong in this case) and some trial and error it appears to be:
- 22 bytes
- plus 76 bytes per file
- plus 2x the length of the path/filename of each file

Adding that to the actual size of the files in the archive, I've been able to use this on roughly 40 different ZIPs of widely varying sizes without issue, and multiple browsers are able to download the file with progress bars, as well as extract the resulting file successfully.  More testing is probably needed though.

Whether you want to implement this in ZipStream or not I don't know, but just thought I'd let anyone else that came across this know that it is possible.

**Comment by NicolasCARPi** [comment]
@ersan Thanks for your insight!

**Comment by lksnmnn** [comment]
I've tried the above calculation, but it did not work using the latest (v2) version of this library. I did play around with available variables and the following calculation gives me the correct size for every download I've tested so far:

- 22 bytes 
- plus 120 bytes for each file
- plus 2x strlen($filename) for each file
- plus actual $filesize for each file

I am not sure why the magic number increased from 76 to 120 without looking at the actual ZIP code, but I might use this for production soon (the UX improvement is great, having the progress bar)

**Comment by ersan** [comment]
Mine is still working, now in production, on everything I've thrown at it.  It could be OS or Filesystem or maybe even character encoding dependent.  Don't know enough about it, honestly.

**Comment by lksnmnn** [comment]
I am using ZipStream v2.1.0 and I do set the `setZeroHeader(true)` option, which probably affects the meta data size. I am streaming all data from _external_ services and do not use the local filesystem. As for OS: Ubuntu 16.04.7 LTS and PHP 7.3.22.

@NicolasCARPi how do you feel about adding a function to ZipStream which is able to calculate the meta data size for uncrompressed ZIP files, so as a user I can safely calculate the total size by adding known filesizes?

**Comment by NicolasCARPi** [comment]
@lksnmnn Pull requests are welcome :) Anything that can make this library better for users will be taken into consideration and reviewed.

**Comment by partiellkorrekt** [comment]
If this helps anyone: I have grown together a small class that wraps ZipStream in a way that it actually uses a content-length header. I disables all the compression for you and also sends out the headers for you.

The API mimics the API of ZipStream.

```php
class Zip
{
  /** @var \ZipStream\ZipStream */
  private $zip;

  private $files = [];

  public function __construct($name)
  {
    $options = new \ZipStream\Option\Archive();
    $options->setSendHttpHeaders(true);
    $options->setEnableZip64(false);
    $options->setDeflateLevel(-1);
    $this->zip = new \ZipStream\ZipStream($name, $options);
  }

  public function addFile($name, $data)
  {
    $this->files[] = ['type' => 'addFile', 'name' => $name, 'data' => $data];
  }

  public function addFileFromPath($name, $path)
  {
    $this->files[] = ['type' => 'addFileFromPath', 'name' => $name, 'path' => $path];
  }

  public function getEstimate()
  {
    $estimate = 22;
    foreach ($this->files as $file) {
      $estimate += 122 + 2 * strlen($file['name']);
      if ($file['type'] === 'addFile') {
        $estimate += strlen($file['data']);
      }
      if ($file['type'] === 'addFileFromPath') {
        $estimate += filesize($file['path']);
      }
    }
    return $estimate;
  }

  public function finish()
  {
    header('Content-Length: ' . $this->getEstimate());
    $fileOptions = new \ZipStream\Option\File();
    $fileOptions->setMethod(\ZipStream\Option\Method::STORE());
    foreach ($this->files as $file) {
      if ($file['type'] === 'addFile') {
        $this->zip->addFile($file['name'], $file['data'], $fileOptions);
      }
      if ($file['type'] === 'addFileFromPath') {
        $this->zip->addFileFromPath($file['name'], $file['path'], $fileOptions);
      }
    }
    $this->zip->finish();
  }
}
```

**Comment by partiellkorrekt** [comment]
@NicolasCARPi There needs to be an update for this code. Apparently 76 bytes extra per file was the correct estimate and the content-length header must be sent before creating the ZipStream-Object in order to prevent warnings about headers:

```php
class Zip
{
  /** @var string */
  private $name;

  private $files = [];

  public function __construct($name)
  {
    $this->name = $name;
  }

  public function addFile($name, $data)
  {
    $this->files[] = ['type' => 'addFile', 'name' => $name, 'data' => $data];
  }

  public function addFileFromPath($name, $path)
  {
    $this->files[] = ['type' => 'addFileFromPath', 'name' => $name, 'path' => $path];
  }

  public function getEstimate()
  {
    $estimate = 22;
    foreach ($this->files as $file) {
      $estimate += 76 + 2 * strlen($file['name']);
      if ($file['type'] === 'addFile') {
        $estimate += strlen($file['data']);
      }
      if ($file['type'] === 'addFileFromPath') {
        $estimate += filesize($file['path']);
      }
    }
    return $estimate;
  }

  public function finish()
  {
    header('Content-Length: ' . $this->getEstimate());
    $options = new \ZipStream\Option\Archive();
    $options->setSendHttpHeaders(true);
    $options->setEnableZip64(false);
    $options->setDeflateLevel(-1);
    $zip = new \ZipStream\ZipStream($this->name, $options);

    $fileOptions = new \ZipStream\Option\File();
    $fileOptions->setMethod(\ZipStream\Option\Method::STORE());
    foreach ($this->files as $file) {
      if ($file['type'] === 'addFile') {
        $zip->addFile($file['name'], $file['data'], $fileOptions);
      }
      if ($file['type'] === 'addFileFromPath') {
        $zip->addFileFromPath($file['name'], $file['path'], $fileOptions);
      }
    }
    $zip->finish();
    exit;
  }
}
```

**Comment by NicolasCARPi** [comment]
updated.
