### ISSUE TITLE
[Wiki] Varnish issue.

### ISSUE THREAD

**Issue by quisse** [maennchen/ZipStream-PHP#98]
# Description of the problem

Serving a big zip with varnish in between can cause random stream close. This can be solved by adding attached code to the vcl file. (created this issue so you can add this to the wiki)

# Solution
```
sub vcl_recv {
    # Varnish can’t intercept the discussion anymore
    # helps for streaming big zips
    if (req.url ~ "\.(tar|gz|zip|7z|exe)$") {
        return (pipe);
    }
}
# Varnish can’t intercept the discussion anymore
# helps for streaming big zips
sub vcl_pipe {
    set bereq.http.connection = "close";
    return (pipe);
}
```

**Comment by NicolasCARPi** [comment]
Hello @quisse,

Thanks for your contribution. The page has been created in the wiki:

https://github.com/maennchen/ZipStream-PHP/wiki/Varnish
